@startuml

actor navegador
boundary routes
boundary "Vista listaReportes.ejs" as list
control controller
entity Report
database mysql


autonumber
activate navegador
navegador -> routes: GET /reportes/rotacion
deactivate navegador
activate routes
routes -> controller: get_reports(req, res)
deactivate routes

activate controller
controller ->> Report: getInfoActivos(start, end)
activate Report
Report ->> mysql: SELECT u.curp AS curp, u.birthName AS nombre, \nu.surname AS apellido, c.title AS pais, r.title AS rol,\n d.title AS departamento FROM user u JOIN userDepartment \nud ON u.userID = ud.userIDFK JOIN department d ON \nud.departmentIDFK = d.departmentID JOIN role r ON u.userRoleIDFK = r.roleID \nJOIN country c ON u.countryUserIDFK = c.countryID\n WHERE u.userID IN ( SELECT u2.userID FROM user u2 \nJOIN workStatus w ON u2.userID = w.userStatusIDFK WHERE u2.workStatus = 1 \nAND w.startDate BETWEEN '2025-03-01' AND '2025-03-31') GROUP BY u.curp ORDER BY d.title;
mysql -->> Report: activeUsers
deactivate mysql
Report -->> controller: Promesa
deactivate Report

controller ->> Report: getInfoInactivos(start, end)
activate Report
Report ->> mysql: SELECT u.curp AS curp, u.birthName AS nombre, \nu.surname AS apellido, c.title AS pais, r.title AS rol, \nd.title AS departamento FROM user u JOIN userDepartment \nud ON u.userID = ud.userIDFK JOIN department d ON \nud.departmentIDFK = d.departmentID JOIN role r ON u.userRoleIDFK = r.roleID JOIN \ncountry c ON u.countryUserIDFK = c.countryID \nWHERE u.userID IN ( SELECT u2.userID FROM user u2 \nJOIN workStatus w ON u2.userID = w.userStatusIDFK WHERE u2.workStatus = 0 \nAND w.endDate BETWEEN '2025-03-01' AND '2025-03-31') GROUP BY u.curp ORDER BY d.title;
activate mysql
mysql -->> Report: inactiveUsers
deactivate mysql
Report -->> controller: Promesa
deactivate Report


controller -> list: res.render('rotacion.ejs', data)
deactivate controller
activate list
list --> navegador: HTML
deactivate list
activate navegador

@enduml
