@startuml

actor navegador
boundary routes
boundary "Vista listaReportes.ejs" as list
control controller
entity Report
database mysql


autonumber
activate navegador
navegador -> routes: GET /reportes/rotacion
deactivate navegador
activate routes
routes -> controller: get_reports(req, res)
deactivate routes

activate controller
controller -> Report: getIDActivos(inicio, final)
deactivate controller
activate Report
Report ->> mysql: execute("SELECT id FROM user u, workStatus w, \nWHERE u.userID = w.userStatusIDFK AND \nu.workstatus = 1 AND w.startDate BETWEEN \n? AND ?", [inicio, final])
activate mysql
mysql -->> Report: Query OK
deactivate mysql
Report --> controller: Promesa
deactivate Report

activate controller
controller -> Report: getInfoActivos(IDs_activos)
deactivate controller
activate Report
Report ->> mysql: execute("SELECT u.* FROM user u, userDepartment ud, department d, \nWHERE u.userID = ud.userIDFK AND ud.deparmentIDFK = d.departmentID \nAND u.userID IN (?) ORDER BY d.name", IDs_activos)
activate mysql
mysql -->> Report: rows
deactivate mysql
Report --> controller: Promesa
deactivate Report

activate controller
controller -> Report: getIDInactivos(inicio, final)
deactivate controller
activate Report
Report ->> mysql: execute("SELECT id FROM user u, workStatus w, \nWHERE u.userID = w.userStatusIDFK AND \nu.workstatus = 0 AND w.endDate BETWEEN \n? AND ?", [inicio, final])
activate mysql
mysql -->> Report: Query OK
deactivate mysql
Report --> controller: Promesa
deactivate Report

activate controller
controller -> Report: getInfoInactivos(IDs_inactivos)
deactivate controller
activate Report
Report ->> mysql: execute("SELECT u.* FROM user u, userDepartment ud, department d, \nWHERE u.userID = ud.userIDFK AND ud.deparmentIDFK = d.departmentID \nAND u.userID IN (?) ORDER BY d.name", IDs_inactivos)
activate mysql
mysql -->> Report: rows
deactivate mysql
Report --> controller: Promesa
deactivate Report

activate controller
controller -> list: res.render('rotacion.ejs', data)
deactivate controller
activate list
list --> navegador: HTML
deactivate list
activate navegador

@enduml
