@startuml
actor navegador
boundary routes
boundary "Vista add.ejs" as add
control controller

autonumber
activate navegador
navegador -> routes: GET /oneonone/add
deactivate navegador
activate routes
routes -> controller: get_add(req, res)
deactivate routes
activate controller
controller -> add: res.render('add.ejs')
deactivate controller
activate add
add -> navegador: HTML
deactivate add

activate navegador
navegador -> routes: POST /oneonone/add
deactivate navegador
activate routes
routes -> controller: post_add(req, res)
deactivate routes


entity OneOnOne
database mysql

activate controller
controller ->> OneOnOne: get_id(req.body.email)
activate OneOnOne
OneOnOne ->> mysql: execute("SELECT userID FROM user \nWHERE mail = ?", \n[email])
activate mysql
mysql -->> OneOnOne: ID del usuario
deactivate mysql
OneOnOne -->> controller: Promesa
deactivate OneOnOne

create entity oneonone
controller -> oneonone : new OneOnOne(req.body.expectedTime, meetingDate, req.body.meetingLink, oneOnOneUserIDFK)
controller ->> oneonone: save()
activate oneonone
oneonone ->> mysql: execute("INSERT INTO OneOnOne \n(?, ?, ?, ?, ?)", [oneToOneID, \nthis.expectedTime, this.meetingDate, \nthis.meetingLink, this.OneOnOneUserIDFK])
activate mysql
mysql --> oneonone: Query OK
deactivate mysql
oneonone -->> controller: promesa
deactivate oneonone

controller -> routes: res.redirect('/oneonone/add', info)
deactivate controller
activate routes
routes -> controller: get_add(req, res)
deactivate routes
activate controller
controller -> add: res.render("add.js", mensaje)
deactivate controller
activate add
add -> navegador: HTML
deactivate add 
activate navegador

@enduml
