@startuml

actor navegador
boundary routes
boundary "Vista add.ejs" as add
boundary "Vista list.ejs" as list
control controller

autonumber
navegador -> routes: GET /absences/add
activate routes
routes -> controller: get_add(req, res)
deactivate routes
activate controller
controller -> add: res.render('add.ejs', sessionVars)
note right: sessionVars es obtenido a través de un util, \ncontiene las variables de sesion y mensajes 
deactivate controller
activate add
add -> navegador: HTML
deactivate add
activate navegador

navegador -> routes: POST /absences/add (req, res)
deactivate navegador
activate routes
routes -> controller: post_add(req, res)
deactivate routes
activate controller

entity Absences

create entity absence
controller -> absence: new Absence(req.body.startDate, req.body.endDate, \nreq.body.reason, req.session.userID)
activate absence
controller ->> absence: save()
database mysql

absence ->> mysql: execute("INSERT INTO absence(?,?,?,?,?,?)",\nabsenceID, this.startDate, this.endDate, \nthis.reason, this.justified, this.absenceUserID )
note left: absenceID es obtenido usando uuid 

activate mysql
mysql -->> absence: Query OK
deactivate mysql
absence -->> controller: promesa
deactivate absence

create entity absenceMedia
controller -> absenceMedia: new AbsenceMedia(req.file.filename, absenceID)
activate absenceMedia
controller ->> absenceMedia : save()

absenceMedia ->> mysql: execute("INSERT INTO absenceMedia(?,?,?)", \nabsenceMediaID, this.mediaLink, this.absenceIDFK)
note left: absenceMediaID es obtenido usando uuid 
activate mysql
mysql -->> absenceMedia: Query OK
deactivate mysql
absenceMedia -->> controller: promesa
deactivate absenceMedia

controller -> routes: res.redirect('/')
deactivate controller

activate routes
routes -> controller: get_root(req, res) 
deactivate routes
activate controller
controller ->> Absences: fetchAllByID(req.session.userID)
activate Absences
Absences ->> mysql: execute("SELECT a.*, am.mediaLink \nFROM absence AS a LEFT JOIN absenceMedia AS am \nON a.absenceID = am.absenceIDFK \nWHERE a.absenceUserIDFK = ? \nORDER BY a.startDate DESC", [req.session.userID])
activate mysql
mysql -->> Absences: rows
deactivate mysql
Absences -->> controller: rows
deactivate Absences

controller -> list: res.render('list.ejs', rows)
deactivate controller
activate list
list -> navegador: HTML
deactivate list
activate navegador

@enduml
