@startuml CU04 - Superadmin registra baja de empleado
|Super Admin|
start
:Seleccionar Baja de empleado;
|Sistema|
:Le pregunta al super admin si esta seguro que quiere dar de baja al colabrador;
|Super Admin|
:Registra respuesta a la pregunta;
|Sistema|
if(¿Quiere dar de baja al empleado?) then (NO)
    :Lo regresa al menu principal;
    stop
else(SI)
    :El sistema modifica la bandera del colaborador de activa a inactiva;
    :Guarda la modificación del colaborador en la base de datos;
    :El sistema notifica al super admin que se dio de baja al colaborador;
    stop
@enduml