@startuml CU05 - Superadmin Elimina dia feriado
|Super Admin|
start
:Seleccionar eliminar asueto;
|Sistema|
:Le pregunta al super admin si esta seguro que quiere eliminar asueto;
|Super Admin|
:Registra respuesta a la pregunta;
|Sistema|
if(¿Quiere eliminar el asueto?) then (NO)
    :Lo regresa al menu principal;
    stop
else(SI)
    :El sistema borra el asueto de la base de datos;
    :El sistema notifica al super admin que se borro correctamente;
    stop
@enduml