@startuml CU018 - Líder registra respuesta hacia ausencia de colaborador - Diagrama de secuencia
actor Navegador
boundary "absence.routes" as Routes
boundary "absence.view" as View
control "absence.controller" as Controller
entity "absence.model" as Model
database "myPhpAdmin" as DB

autonumber

' El Navegador envía la petición AJAX para registrar la respuesta a la ausencia
activate Navegador
Navegador ->> Routes: POST /absence/requests/:id

activate Routes
Routes -> Controller: getRequests(request, response)
deactivate Routes
activate Controller

' El controlador invoca al modelo para actualizar la respuesta de la ausencia
Controller ->> Model: fetchPaginated(responseData, absenceID)
activate Model

' El modelo ejecuta la consulta en la base de datos
Model ->> DB: db.execute(\n"UPDATE absence SET leaderStatus = ? WHERE absenceID = ?", \n[userId, limit, offset])
activate DB
DB -->> Model: rows
deactivate DB

Model -->> Controller: rows
deactivate Model

' El controlador procesa el resultado y prepara la respuesta para la vista (AJAX JSON o fragmento HTML)
Controller -->> Navegador: render(absenceRequests)
deactivate Controller


' El Navegador procesa la respuesta y actualiza la interfaz
Navegador -> Navegador: loadPage, actualiza UI

@enduml