@startuml CU02 - Superadmin registra respuesta hacia solicitud de vacaciones de empleado - Diagrama de secuencia
actor Navegador
boundary "vacation.routes" as Routes
boundary "vacation.view" as View
control "vacation.controller" as Controller
entity "vacation.model" as Model
database "myPhpAdmin" as DB

autonumber

' El SuperAdmin (HR) envía la respuesta a través de AJAX
activate Navegador
Navegador -> Routes: POST /vacation/registerResponse (AJAX)

activate Routes
Routes -> Controller: registerResponse(request, response)
activate Controller

' El controlador actualiza la respuesta de la solicitud en el modelo
Controller ->> Model: updateVacationResponse(responseData, vacationID)
activate Model
Model ->> DB: db.execute("\nUPDATE vacation_requests \nSET response = ? \nWHERE vacationID = ?", \n[responseData, vacationID])
activate DB
DB -->> Model: confirmación de actualización
deactivate DB
Model -->> Controller: updateResult
deactivate Model

' Se prepara la respuesta para el cliente a través de la vista
Controller ->> View: renderResponse(updateResult)
activate View
View --> Controller: fragmento HTML/JSON
deactivate View

Controller -->> Routes: response.json()
deactivate Controller

Routes -->> Navegador: respuesta AJAX
deactivate Routes

Navegador -> Navegador: Callback actualiza la interfaz
deactivate Navegador

@enduml
