@startuml CU09 - Cambio de contraseña temporal - Diagrama de secuencia

actor Navegador
boundary "myprofile.routes" as Routes
boundary "myprofile.ejs" as View
control "myprofile.controller" as Controller
entity "user.model" as Model
database "mySQL" as DB

autonumber

' El navegador envía una solicitud POST para cambiar la contraseña
activate Navegador
Navegador -> Routes : GET /changePassword
deactivate Navegador

' La ruta redirige a la vista del formulario
activate Routes
Routes -> Controller : changePassword
deactivate Routes
activate Controller

Controller -> Navegador : HTML
deactivate Controller
deactivate View
activate Navegador
Navegador -> Controller : POST /changePassword
deactivate Navegador


' El controlador valida la contraseña en el servidor
activate Controller
Controller -> Controller : validatePassword(newPassword)
alt La contraseña no es segura
    Controller -> View : renderChangePassword(error="Contraseña no segura")
    activate View
    View -> Navegador : HTML
    deactivate View
end
' La contraseña es segura
' Se aplica el hash internamente antes de actualizar la contraseña en la base de datos.
Controller -> Model : updatePassword(newPassword, userID)
activate Model
Model -> DB : db.execute("UPDATE user\nSET passwd = ? ,\npasswdFlag = ture\nWHERE userID = ?",\n[newPassword, userID])
deactivate Model
activate DB
DB -> Controller : success(status=True)
deactivate DB
deactivate View
Controller -> Navegador : redirect(home)
deactivate Controller
activate Navegador

@enduml