@startuml CU017 - Líder consulta respuesta hacia ausencia de colaborador - Diagrama de secuencia
actor Navegador
boundary "absence.routes" as Routes
boundary "absence.view" as View
control "absence.controller" as Controller
entity "absence.model" as Model
database "myPhpAdmin" as DB

autonumber

' El Navegador envía la petición AJAX para registrar la respuesta a la ausencia
activate Navegador
Navegador ->> Routes: GET /absence/requests

activate Routes
Routes -> Controller: getRequests(request, response)
deactivate Routes
activate Controller

' El controlador invoca al modelo para actualizar la respuesta de la ausencia
Controller ->> Model: fetchPaginated(responseData, absenceID)
activate Model

' El modelo ejecuta la consulta en la base de datos
Model ->> DB: db.execute(\n"SELECT a.*, u.birthName, u.surname, r.title \nFROM absence AS a \nJOIN user AS u ON u.userID = a.absenceUserIDFK \nJOIN role AS r ON r.roleID = u.userRoleIDFK \nWHERE a.hrStatus = 2 \nORDER BY a.startDate DESC LIMIT ? OFFSET ?", \n[limit, offset, userRole, userId])
activate DB
DB -->> Model: rows
deactivate DB

Model -->> Controller: rows
deactivate Model

' El controlador procesa el resultado y prepara la respuesta para la vista (AJAX JSON o fragmento HTML)
Controller -->> Navegador: render(absenceRequests)
deactivate Controller


' El Navegador procesa la respuesta y actualiza la interfaz
Navegador -> Navegador: loadPage, actualiza UI

@enduml