@startuml CU01 - Líder consulta solicitudes de vacaciones de colaborador - Diagrama de actividad

|__Líder__|
start
:Selecciona opción\n "Solicitudes de ausencias";

|__Sistema__|
if(Verificar que existen >1 solicitudes\n de ausencias pendientes) then (Sí)
    :Despliega en forma de tabla\n todas las solicitudes de ausencias.;
else (No)
    :Despliega en forma de tabla\n. Muestra mensaje al líder que\nno existen solicitudes pendientes;
    stop
endif

|__Líder__|
:De una solicitud, da click\n en aceptar o denegar solicitud.;

|__Sistema__|
:Registra la respuesta en la base de datos\n y muestra el cambio al líder.;

|__Líder__|
:Presiona el botón de cerrar;

stop

@enduml