@startuml CU019 - Líder registra solicitudes de ausecia de colaborador - Diagrama de actividad

|__Líder__|
start
:Selecciona opción\n "Solicitudes de ausencias";

|__Sistema__|
:Obtiene las últimas 10 solicitudes de ausencias;

:Despliega en forma de tabla las solicitudes;

|__Líder__|
:De una solicitud, da click\n en aceptar o denegar solicitud.;

|__Sistema__|
:Registra la respuesta en la base de datos\n y muestra el cambio al líder.;

|__Líder__|
:Presiona el botón de cerrar;

stop

@enduml