@startuml CU02 - SuperAdmin consulta solicitudes de vacaciones de colaborador - Diagrama de actividad

|__SuperAdmin__|
start
:Selecciona opción\n"Solicitudes de vacaciones";

|__Sistema__|
:Obtiene las últimas 10 solicitudes de vacaciones;
:Despliega en forma de tabla las solicitudes.;

|__SuperAdmin__|
:De una solicitud, da click\nen aceptar o denegar solicitud.;

|__Sistema__|
:Registra la respuesta en la base de datos\ny muestra el cambio al líder.;

|__SuperAdmin__|
:Presiona el botón de cerrar;

stop

@enduml