@startuml CU02 - SuperAdmin consulta solicitudes de vacaciones de colaborador - Diagrama de actividad

|__SuperAdmin__|
start
:Selecciona opción\n"Solicitudes de vacaciones";

|__Sistema__|
if(Verificar que existen >1 solicitudes\nde vacaciones pendientes) then (Sí)
    :Despliega en forma de tabla\ntodas las solicitudes de vacaciones.;
else (No)
    :Despliega en forma de tabla.\nMuestra mensaje al líder que\nno existen solicitudes pendientes;
    stop
endif

|__SuperAdmin__|
:Se finaliza el proceso;

stop

@enduml