INSERT INTO privilege(title, summary) values('User A does this', 'Another privilege more??'); 
INSERT INTO privilege(title, summary) values('And user C does this', 'Another privilege more??'); 
INSERT INTO privilege(title, summary) values('User A does this', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('And user C does this', 'This is a privilege'); 
INSERT INTO privilege(title, summary) values('User B does this other thing', 'This is a privilege'); 
INSERT INTO privilege(title, summary) values('While user D still does this', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('User B does this other thing', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('While user D still does this', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('While user D still does this', 'Another privilege more??'); 
INSERT INTO privilege(title, summary) values('And user C does this', 'This is a privilege'); 

INSERT INTO role(title) values('Colaborator'); 
INSERT INTO role(title) values('Department Leader'); 
INSERT INTO role(title) values('Human Resources'); 

INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 4); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 5); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 2); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 2); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 7); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 8); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 4); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 6); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 6); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 1); 

INSERT INTO country(title) values('Mexico'); 
INSERT INTO country(title) values('United States'); 
INSERT INTO country(title) values('Colombia'); 
INSERT INTO country(title) values('Argentina'); 

INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Vázquez', 'jhgjxtnbogk@outlook.com', 'yyvoidxquuyh', TRUE, 11009, '726.B', 'Calle Allende', 'Colonia Los Ángeles', 2, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Díaz', 'dhhmqnlas@gmail.com', 'ckubeydg', TRUE, 11466, '245.C', 'Avenida de la Luz', 'Colonia El Laurel', 3, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Torres', 'ejftggnogn@gmail.com', 'atvduik', FALSE, 17343, '281.B', 'Calle Juárez', 'Colonia Reforma', 1, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'Jiménez', 'nwohhtpufa@gmail.com', 'obppiknpdbmo', FALSE, 41887, '98.A', 'Avenida de la Luz', 'Colonia Nuevo Milenio', 0, TRUE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Díaz', 'unprxabvd@yahoo.com', 'hscsmrf', TRUE, 36002, '184.A', 'Calle de la Paz', 'Colonia San Francisco', 3, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Martínez', 'ngjlwxvhiu@gmail.com', 'jmimdervxu', FALSE, 27122, '181.A', 'Calle de la Estación', 'Colonia Santa Rosa', 1, TRUE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'López', 'ndytlvtwqdiqx@gmail.com', 'uqurlmnfo', TRUE, 15962, '376.A', 'Avenida de los Insurgentes', 'Colonia Santa Rosa', 3, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'López', 'idinnrw@yahoo.com', 'lhbgvgilec', FALSE, 15691, '15.A', 'Avenida Constituyentes', 'Colonia La Pradera', 2, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Torres', 'tgahwibhej@outlook.com', 'txyettcqaqgtu', TRUE, 41876, '153.C', 'Avenida de la Luz', 'Colonia Centro', 2, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Rodríguez', 'llyxhwoyth@gmail.com', 'llacqpvs', TRUE, 36424, '141.A', 'Avenida de la Juventud', 'Colonia Reforma', 0, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'Rodríguez', 'hbulqxlfn@yahoo.com', 'vljgnqx', FALSE, 16352, '948.C', 'Avenida de la Independencia', 'Colonia Santa Rosa', 1, TRUE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Gómez', 'trdxpfdwrjt@outlook.com', 'unxvcbgftsf', TRUE, 12037, '305.B', 'Calle de la Virgen', 'Colonia Santa Rosa', 3, FALSE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Moreno', 'dbweoejhxmu@outlook.com', 'ptcibhp', TRUE, 19998, '175.B', 'Avenida Madero', 'Colonia Emiliano Zapata', 3, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Moreno', 'bwuegpoafeal@outlook.com', 'airvqmew', TRUE, 32748, '574.A', 'Avenida de la Juventud', 'Colonia La Pradera', 3, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Moreno', 'wsaiexafdwgi@gmail.com', 'rmlvjor', TRUE, 34904, '573.C', 'Calle del Carmen', 'Colonia El Campanario', 2, TRUE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Pérez', 'efxfapu@gmail.com', 'sdlpiyrjw', TRUE, 42421, '412.C', 'Avenida Universidad', 'Colonia El Campanario', 2, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'González', 'qcrcnwj@nuclea.solutions', 'klutacyvyoi', FALSE, 15012, '804.A', 'Calle Vicente Guerrero', 'Colonia Los Ángeles', 1, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Sánchez', 'ehbvkhsrxq@outlook.com', 'bpfeokawaast', FALSE, 19484, '618.C', 'Calle de la Merced', 'Colonia El Cerrito', 2, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Vázquez', 'mvdmbjhmbjv@yahoo.com', 'prfbfidlelrdg', TRUE, 36842, '979.C', 'Avenida Revolución', 'Colonia Lomas de Querétaro', 1, TRUE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Pérez', 'jfdiopnsbxrl@outlook.com', 'bjaulomptpwcy', TRUE, 19702, '908.A', 'Calle Allende', 'Colonia Reforma', 1, TRUE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Hernández', 'enleeaub@outlook.com', 'lgshhwyubidwy', TRUE, 26930, '26.A', 'Avenida de la Libertad', 'Colonia Valle Verde', 1, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Pérez', 'tvopcvfrb@nuclea.solutions', 'erobick', TRUE, 14358, '639.C', 'Calle Juárez', 'Colonia del Sol', 1, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Sánchez', 'uiroudxk@gmail.com', 'lknnwlh', FALSE, 16838, '479.A', 'Calle de la Merced', 'Colonia Reforma', 0, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'Gómez', 'slkasryvwjsb@gmail.com', 'pstovabpr', FALSE, 10683, '222.B', 'Calle Benito Juárez', 'Colonia Emiliano Zapata', 0, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Fernández', 'rrgwquxubqelk@yahoo.com', 'bbgmdpjipeia', FALSE, 40546, '346.C', 'Avenida de la Independencia', 'Colonia El Cerrito', 2, FALSE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'González', 'mbjdtkcme@nuclea.solutions', 'mpnjxnqblwdkk', FALSE, 13973, '162.C', 'Avenida de la Solidaridad', 'Colonia El Campanario', 2, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Sánchez', 'fcyctbvtwbkte@outlook.com', 'xlawlrmrmfff', TRUE, 41485, '805.C', 'Calle de la Merced', 'Colonia El Campanario', 3, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'Rodríguez', 'micilnjft@nuclea.solutions', 'cjpklpd', FALSE, 28241, '876.C', 'Calle de la Corregidora', 'Colonia Nuevo Milenio', 3, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Rodríguez', 'xabgwcf@gmail.com', 'crapqgvgs', TRUE, 23039, '988.C', 'Avenida de la Solidaridad', 'Colonia Los Ángeles', 0, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Gómez', 'poevgxbfwuhfp@nuclea.solutions', 'eaxchyhjcld', FALSE, 15440, '761.A', 'Calle Juárez', 'Colonia El Laurel', 0, FALSE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Sánchez', 'omskxlv@outlook.com', 'lnjxinjfp', FALSE, 23394, '736.C', 'Calle Juárez', 'Colonia La Pradera', 1, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Vázquez', 'lcfuaaaqm@gmail.com', 'sukmqbnhfx', FALSE, 19947, '334.C', 'Avenida Universidad', 'Colonia Jardines de Querétaro', 3, TRUE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Martínez', 'xfgqhoecowi@gmail.com', 'ngtxklsyglgrp', FALSE, 23167, '156.A', 'Calle de la Esperanza', 'Colonia Jardines de Querétaro', 1, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Sánchez', 'bjmnsrnco@yahoo.com', 'vmckjqu', FALSE, 36845, '163.C', 'Avenida Constituyentes', 'Colonia Santa Fe', 2, TRUE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Moreno', 'lbhdkng@nuclea.solutions', 'agpicpi', FALSE, 27808, '74.A', 'Calle de la Esperanza', 'Colonia Centro', 1, FALSE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Sánchez', 'ivgucjys@nuclea.solutions', 'tcfmxegdbx', FALSE, 14339, '945.A', 'Calle Benito Juárez', 'Colonia El Mirador', 2, TRUE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Pérez', 'mpfoxrir@gmail.com', 'xurinfpuc', TRUE, 25198, '22.C', 'Calle Allende', 'Colonia Santa Fe', 1, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Martínez', 'buvotawt@gmail.com', 'xtiisofjpcswl', TRUE, 15972, '35.C', 'Avenida de la Independencia', 'Colonia El Campanario', 1, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Hernández', 'elpxhkcxddf@outlook.com', 'byhuiee', FALSE, 18012, '892.C', 'Avenida Constituyentes', 'Colonia Las Águilas', 2, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Moreno', 'wtqqwkvr@gmail.com', 'jtuttfr', TRUE, 42568, '263.C', 'Calle Vicente Guerrero', 'Colonia del Sol', 0, TRUE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Vázquez', 'ehvpsjhyvr@gmail.com', 'udhajwfotyr', TRUE, 25874, '719.C', 'Calle de la Esperanza', 'Colonia San José', 1, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'Moreno', 'svdmrjtflchks@yahoo.com', 'volprrbbkatek', FALSE, 18243, '83.B', 'Avenida Constituyentes', 'Colonia El Mirador', 3, TRUE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Martínez', 'pijrvwsb@gmail.com', 'wsuqkssm', FALSE, 31010, '88.B', 'Calle Corregidora', 'Colonia Morelos', 1, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Fernández', 'hktuaog@outlook.com', 'qhskvnfeqft', TRUE, 13797, '427.B', 'Avenida Madero', 'Colonia El Cerrito', 2, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'Martínez', 'eevpwkjvqrfly@gmail.com', 'kgtedoeohn', TRUE, 34602, '569.B', 'Avenida de la Libertad', 'Colonia La Pradera', 2, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Vázquez', 'tbvaxylhpmfw@outlook.com', 'lmwcsunurgvqi', FALSE, 13044, '968.C', 'Calle del Carmen', 'Colonia El Campanario', 0, TRUE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'López', 'vwrhlhvtruqx@yahoo.com', 'arntlniu', FALSE, 20285, '181.C', 'Calle Juárez', 'Colonia El Mirador', 1, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Rodríguez', 'olmnbty@outlook.com', 'bundyba', FALSE, 34281, '541.B', 'Calle Vicente Guerrero', 'Colonia San Francisco', 2, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Moreno', 'ylejqylf@outlook.com', 'gtkdhkxu', TRUE, 24962, '729.A', 'Calle de la Virgen', 'Colonia San José', 0, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'López', 'hymakfs@yahoo.com', 'ootlhjxylwpgf', FALSE, 23832, '981.B', 'Calle Vicente Guerrero', 'Colonia Jardines de Querétaro', 2, TRUE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Juan', 'Sánchez', 'shccqxuqigx@nuclea.solutions', 'ulhflpabtsip', FALSE, 36967, '130.A', 'Calle Zaragoza', 'Colonia Jardines de Querétaro', 3, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Martínez', 'lypnkebyqew@yahoo.com', 'rfbjtlg', FALSE, 42365, '4.C', 'Avenida de la Juventud', 'Colonia El Cerrito', 0, TRUE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'López', 'snkgdsgeeg@outlook.com', 'mbdlbxm', TRUE, 39418, '286.C', 'Calle Vicente Guerrero', 'Colonia Emiliano Zapata', 1, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Sánchez', 'fahgxsfslv@yahoo.com', 'pfefhasprqj', TRUE, 35060, '516.C', 'Avenida Revolución', 'Colonia Centro', 0, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'Rodríguez', 'hccvevpmtoxee@outlook.com', 'owjetys', TRUE, 25275, '224.B', 'Avenida Constituyentes', 'Colonia El Laurel', 1, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Roberto', 'Fernández', 'elheqkch@outlook.com', 'sinbowcd', FALSE, 11549, '98.C', 'Calle Allende', 'Colonia Nuevo Milenio', 1, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'González', 'qxkbmjiwqsg@gmail.com', 'pgsmnflek', TRUE, 35985, '430.A', 'Calle de la Esperanza', 'Colonia Valle Verde', 0, TRUE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Jiménez', 'yamxeytbisre@nuclea.solutions', 'qegoaqbrjtit', TRUE, 25145, '321.C', 'Avenida de los Insurgentes', 'Colonia Emiliano Zapata', 2, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'Sánchez', 'tdubhyn@nuclea.solutions', 'wgmbyapdth', TRUE, 29079, '328.B', 'Calle de los Naranjos', 'Colonia Nuevo Milenio', 1, TRUE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Juan', 'Jiménez', 'pncsyaempfduf@yahoo.com', 'njrtfdxbvwxfm', TRUE, 38404, '150.B', 'Avenida de la Independencia', 'Colonia El Laurel', 1, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Martínez', 'iqovchpier@gmail.com', 'hqtxewf', FALSE, 36622, '552.B', 'Calle de los Naranjos', 'Colonia Reforma', 2, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'González', 'fwtnryqreco@outlook.com', 'mdoovoagjd', TRUE, 40755, '257.C', 'Calle Allende', 'Colonia Santa Fe', 0, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Gómez', 'cetiosxwewa@gmail.com', 'dxacaeotiai', TRUE, 35971, '497.B', 'Calle de la Corregidora', 'Colonia Reforma', 3, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Vázquez', 'frultpe@nuclea.solutions', 'sudklnwcx', TRUE, 29126, '764.C', 'Calle de los Pinos', 'Colonia El Campanario', 1, FALSE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Hernández', 'mfeymjpcglrgh@gmail.com', 'trfloteylja', TRUE, 41843, '957.A', 'Calle de la Paz', 'Colonia Reforma', 1, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'Díaz', 'glgfnhlepw@outlook.com', 'ylxhgfdpqokn', TRUE, 34403, '490.A', 'Avenida de la Libertad', 'Colonia San José', 1, TRUE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Fernández', 'mvlrvarqffn@outlook.com', 'froxdlepw', TRUE, 21845, '660.C', 'Avenida Universidad', 'Colonia Santa Rosa', 0, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Díaz', 'hbayeoyuk@outlook.com', 'ijthncvohfkbx', TRUE, 12839, '175.A', 'Calle de los Cedros', 'Colonia Reforma', 3, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Martínez', 'utxpnpbl@outlook.com', 'dkvbweqio', TRUE, 26193, '785.C', 'Calle de la Esperanza', 'Colonia El Laurel', 2, TRUE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Fernández', 'txmhatpoklr@nuclea.solutions', 'hjviykxtdl', TRUE, 18301, '537.A', 'Calle de los Naranjos', 'Colonia El Cerrito', 0, FALSE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Hernández', 'qrmlvwxedxk@nuclea.solutions', 'ysdvxgdlor', TRUE, 37964, '57.C', 'Avenida Morelos', 'Colonia El Cerrito', 1, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Vázquez', 'ryufaht@nuclea.solutions', 'lrcniuq', FALSE, 32427, '695.A', 'Avenida Constituyentes', 'Colonia Morelos', 1, TRUE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Vázquez', 'cfkyvdmywkct@gmail.com', 'jghulvakdx', FALSE, 40724, '412.A', 'Avenida Constituyentes', 'Colonia Los Ángeles', 2, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'López', 'gxflitnqy@yahoo.com', 'visebjmifx', TRUE, 20444, '854.A', 'Calle Vicente Guerrero', 'Colonia Santa Fe', 3, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'González', 'buyygeyvrtfy@nuclea.solutions', 'gusufsfm', TRUE, 10460, '224.C', 'Calle 5 de Febrero', 'Colonia Reforma', 0, TRUE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Sánchez', 'rvnkrfbewhrfe@yahoo.com', 'adadruhe', FALSE, 14713, '603.A', 'Calle 5 de Febrero', 'Colonia La Pradera', 1, TRUE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Hernández', 'hrbwsuse@nuclea.solutions', 'wqefsbhnljj', TRUE, 41158, '141.B', 'Calle Benito Juárez', 'Colonia del Sol', 0, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Rodríguez', 'kwwlvtdw@gmail.com', 'ifuqwgaylcqg', TRUE, 12468, '325.B', 'Avenida Universidad', 'Colonia San José', 0, TRUE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'Hernández', 'ucurrxkkgdp@nuclea.solutions', 'jjgpxwr', TRUE, 11163, '107.C', 'Calle de los Cedros', 'Colonia Las Águilas', 3, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'Gómez', 'brknxjroxbonl@outlook.com', 'lvrkoujsj', TRUE, 23679, '460.B', 'Calle Allende', 'Colonia Jardines de Querétaro', 2, TRUE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'Pérez', 'iprlwtwwm@gmail.com', 'jpuyeoswmhif', FALSE, 33500, '331.A', 'Calle de la Merced', 'Colonia Santa Fe', 0, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Sánchez', 'yigyiaqw@outlook.com', 'dlxqgxa', TRUE, 22354, '280.C', 'Calle Vicente Guerrero', 'Colonia del Sol', 1, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'González', 'irrccixgfvh@nuclea.solutions', 'nxuepldj', FALSE, 23369, '217.A', 'Calle Vicente Guerrero', 'Colonia Los Ángeles', 3, FALSE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Moreno', 'xiabydv@nuclea.solutions', 'uitxwwkmpj', TRUE, 27642, '653.A', 'Avenida de la Juventud', 'Colonia Centro', 2, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Moreno', 'xkorjhxg@gmail.com', 'ivaxmogqg', TRUE, 19937, '273.C', 'Calle de los Abetos', 'Colonia Jardines de Querétaro', 0, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Hernández', 'oviqkyfkmvfxj@nuclea.solutions', 'ogcqcqbwjgklr', TRUE, 22795, '848.C', 'Calle de la Santa Cruz', 'Colonia Centro', 3, FALSE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Moreno', 'eheaeqv@outlook.com', 'qnegytpend', FALSE, 28298, '839.C', 'Avenida de los Insurgentes', 'Colonia Nuevo Milenio', 0, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Jiménez', 'wwkfsadrfj@gmail.com', 'cjhwiilbqchsl', TRUE, 13234, '421.B', 'Avenida Revolución', 'Colonia Santa Fe', 0, TRUE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Martínez', 'axamwbgait@nuclea.solutions', 'whkggpticrmi', TRUE, 25733, '296.B', 'Calle de la Paz', 'Colonia Emiliano Zapata', 3, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'López', 'rkccxwfa@yahoo.com', 'wqjrbvxrm', TRUE, 27097, '145.B', 'Avenida Universidad', 'Colonia El Campanario', 1, TRUE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Pérez', 'iewsekljmlq@nuclea.solutions', 'odjkeffk', TRUE, 37894, '588.C', 'Avenida de la Solidaridad', 'Colonia La Pradera', 2, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Fernández', 'xlpipvgigpced@outlook.com', 'sljkmjh', TRUE, 28385, '691.B', 'Calle de los Cedros', 'Colonia Los Ángeles', 3, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Martínez', 'bgwspsefi@nuclea.solutions', 'pcfcuuw', FALSE, 29291, '197.C', 'Calle Juárez', 'Colonia San Francisco', 2, TRUE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'González', 'chndmfyii@nuclea.solutions', 'koiwoco', TRUE, 11456, '293.C', 'Avenida de la Luz', 'Colonia Santa Fe', 0, FALSE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Jiménez', 'bolloklckog@nuclea.solutions', 'buqlirdt', TRUE, 35057, '437.A', 'Calle de la Reforma', 'Colonia Santa Fe', 1, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Pérez', 'falpvauvys@gmail.com', 'yorasamkopjc', FALSE, 31392, '345.C', 'Calle Zaragoza', 'Colonia El Laurel', 0, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Vázquez', 'bomiotgxdjdfb@outlook.com', 'hnjkowmpaqobc', FALSE, 39280, '5.C', 'Calle Juárez', 'Colonia El Mirador', 1, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Moreno', 'keflbgkunquun@nuclea.solutions', 'hkgqmga', FALSE, 34736, '125.C', 'Calle de los Cedros', 'Colonia Valle Verde', 2, FALSE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Jiménez', 'kxqvbkkvremas@outlook.com', 'crbedcsld', TRUE, 26255, '839.A', 'Avenida de la Solidaridad', 'Colonia del Sol', 2, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'Ruiz', 'eojnjoydej@outlook.com', 'gftpxvfh', TRUE, 12435, '244.C', 'Calle Hidalgo', 'Colonia El Campanario', 2, TRUE, 1, 4);

INSERT INTO oneOnOneQuestion(question) VALUES('¿De qué estás orgulloso del mes pasado?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿El trabajo y las entregas van en el tiempo planeado?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿A quién quiero reconocer en la semana?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿A quién quiero reconocer en la semana?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Tuviste alguna situación complicada en tu semana que afectara en tu trabajo?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿En qué te encuentras trabajando?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Tuviste alguna situación complicada en tu semana que afectara en tu trabajo?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Cuál va a ser tu meta del mes?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Cuentas con los recursos necesarios para completar tu trabajo?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿De qué estás orgulloso del mes pasado?'); 

INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica El colaborador menciona tener una salud fisica un poco mala'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica: El colaborador menciona tener una salud fisica buena'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Reconocimiento: El colaborador se siente poco valorado por sus compañeros'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Reconocimiento: El colaborador se siente valorado por sus compañeros'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Equiilibrio: El colaborador siente que hay poco equilibrio entre su vida personal y trabajo'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Equiilibrio: El colaborador siente que hay poco equilibrio entre su vida personal y trabajo'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Reconocimiento: El colaborador se siente poco valorado por sus compañeros'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Carga de trabajo El colaborador siente que su carga de trabajo no es manejable'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica El colaborador menciona tener una salud fisica regular'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica El colaborador menciona tener una salud fisica un poco mala'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Equiilibrio: El colaborador siente que hay poco equilibrio entre su vida personal y trabajo'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente excelente emocionalmente y con emociones muy positivas'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Equiilibrio: El colaborador siente que hay poco equilibrio entre su vida personal y trabajo'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente mal emocionalmente y con emociones poco positivas'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Carga de trabajo: El colaborador siente que su carga es medianamente manejable'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Carga de trabajo: El colaborador siente que su carga es medianamente manejable'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica: El colaborador menciona tener una salud fisica excelente'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica: El colaborador menciona tener una salud fisica mala'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica El colaborador menciona tener una salud fisica un poco mala'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente muy bien emocionalmente y con emociones positivas'); 

INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:00:00', 63);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:15:00', 26);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:30:00', 17);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:30:00', 45);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:45:00', 51);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:00:00', 11);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 40);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:45:00', 18);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:15:00', 88);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:30:00', 39);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:15:00', 68);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:00:00', 26);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:00:00', 41);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:30:00', 28);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:30:00', 18);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 14);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:15:00', 28);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:30:00', 16);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:30:00', 35);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:30:00', 95);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:15:00', 84);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:45:00', 38);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:00:00', 11);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:15:00', 95);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:15:00', 34);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:30:00', 65);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:45:00', 54);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:30:00', 52);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:30:00', 76);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:15:00', 32);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:00:00', 67);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:15:00', 61);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:45:00', 3);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:45:00', 8);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:30:00', 30);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 75);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:15:00', 96);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:15:00', 77);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:45:00', 47);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:15:00', 42);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:15:00', 78);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:00:00', 10);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:15:00', 3);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:30:00', 22);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:15:00', 82);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:45:00', 88);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:15:00', 59);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:00:00', 88);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:15:00', 75);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:45:00', 41);

INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, hubo un imprevisto en la coordinación del equipo, pero logramos resolverlo a tiempo con la colaboración de todos.', 5, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me encuentro trabajando en la optimización de procesos internos y en la implementación de mejoras para el próximo trimestre.', 49, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Planeamos definir un plan de acción detallado, distribuir responsabilidades claramente y realizar seguimientos semanales para ajustar el rumbo si es necesario.', 29, 3);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En general tengo lo necesario, aunque en algunas áreas podría beneficiarme de recursos adicionales para acelerar ciertos procesos.', 7, 6);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En general, me siento tranquilo, aunque reconozco que en algunas situaciones se presenta algo de estrés que manejo con calma.', 48, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me siento orgulloso de haber cumplido mis objetivos en el proyecto X, lo que me permitió crecer profesionalmente.', 28, 3);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Quiero destacar el esfuerzo y la colaboración de todo el equipo, que ha sido fundamental para alcanzar los objetivos planteados.', 6, 6);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 42, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me siento orgulloso de haber cumplido mis objetivos en el proyecto X, lo que me permitió crecer profesionalmente.', 30, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 16, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Planeamos definir un plan de acción detallado, distribuir responsabilidades claramente y realizar seguimientos semanales para ajustar el rumbo si es necesario.', 36, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, cuento con las herramientas y el apoyo necesario, lo que me permite avanzar sin mayores inconvenientes.', 9, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Estoy satisfecho por haber superado varios desafíos y mejorar mi organización y gestión del tiempo.', 35, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Planeamos definir un plan de acción detallado, distribuir responsabilidades claramente y realizar seguimientos semanales para ajustar el rumbo si es necesario.', 34, 1);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Mi meta es finalizar el proyecto pendiente y comenzar a implementar nuevas estrategias para mejorar la productividad.', 29, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 17, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me encuentro trabajando en la optimización de procesos internos y en la implementación de mejoras para el próximo trimestre.', 5, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('La mayoría de las entregas están en línea con el cronograma, aunque se requieren pequeños ajustes en algunas tareas.', 11, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 39, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 4, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, hubo un imprevisto en la coordinación del equipo, pero logramos resolverlo a tiempo con la colaboración de todos.', 36, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Mi meta es finalizar el proyecto pendiente y comenzar a implementar nuevas estrategias para mejorar la productividad.', 10, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 36, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Quiero destacar el esfuerzo y la colaboración de todo el equipo, que ha sido fundamental para alcanzar los objetivos planteados.', 4, 1);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, cuento con las herramientas y el apoyo necesario, lo que me permite avanzar sin mayores inconvenientes.', 12, 6);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, cuento con las herramientas y el apoyo necesario, lo que me permite avanzar sin mayores inconvenientes.', 38, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 7, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 39, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 36, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me encuentro trabajando en la optimización de procesos internos y en la implementación de mejoras para el próximo trimestre.', 3, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Mi meta es finalizar el proyecto pendiente y comenzar a implementar nuevas estrategias para mejorar la productividad.', 25, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Por el momento, estamos cumpliendo los plazos establecidos y el progreso es consistente.', 2, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me siento orgulloso de haber cumplido mis objetivos en el proyecto X, lo que me permitió crecer profesionalmente.', 37, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Por el momento, estamos cumpliendo los plazos establecidos y el progreso es consistente.', 28, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 21, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Quiero concentrarme en perfeccionar mis habilidades técnicas y cumplir con los plazos establecidos en mis tareas.', 20, 3);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me encuentro trabajando en la optimización de procesos internos y en la implementación de mejoras para el próximo trimestre.', 32, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, cuento con las herramientas y el apoyo necesario, lo que me permite avanzar sin mayores inconvenientes.', 2, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 27, 6);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Por el momento, estamos cumpliendo los plazos establecidos y el progreso es consistente.', 5, 3);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Mi meta es finalizar el proyecto pendiente y comenzar a implementar nuevas estrategias para mejorar la productividad.', 12, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Mi meta es finalizar el proyecto pendiente y comenzar a implementar nuevas estrategias para mejorar la productividad.', 17, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, cuento con las herramientas y el apoyo necesario, lo que me permite avanzar sin mayores inconvenientes.', 11, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Por el momento, estamos cumpliendo los plazos establecidos y el progreso es consistente.', 21, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, hubo un imprevisto en la coordinación del equipo, pero logramos resolverlo a tiempo con la colaboración de todos.', 45, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Mi meta es finalizar el proyecto pendiente y comenzar a implementar nuevas estrategias para mejorar la productividad.', 10, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Mi meta es finalizar el proyecto pendiente y comenzar a implementar nuevas estrategias para mejorar la productividad.', 2, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('La mayoría de las entregas están en línea con el cronograma, aunque se requieren pequeños ajustes en algunas tareas.', 33, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Vamos a fomentar la comunicación continua y a utilizar herramientas de gestión que nos ayuden a monitorear el progreso.', 45, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En general tengo lo necesario, aunque en algunas áreas podría beneficiarme de recursos adicionales para acelerar ciertos procesos.', 7, 10);

INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 48, 8);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 13, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 45, 20);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 48, 13);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 4, 16);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 48, 19);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 9, 17);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 14, 14);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 4, 11);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 30, 13);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 38, 19);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 6, 8);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 32, 14);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 12, 17);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 6, 11);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 28, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 25, 20);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 7, 3);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 1, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 6, 1);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 23, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 23, 3);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 41, 11);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 34, 2);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 33, 18);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 44, 9);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 36, 19);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 47, 11);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 44, 17);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 43, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 14, 7);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 6, 1);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 33, 19);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 44, 7);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 32, 3);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 46, 8);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 42, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 7, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 22, 20);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 14, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 11, 20);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 33, 15);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 30, 1);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 44, 2);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 12, 3);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 18, 8);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 20, 17);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 38, 11);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 6, 10);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 9, 18);

INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-12', 'El empleado no se presenta al trabajo sin avisar o sin una razón válida, afectando la continuidad de las labores del equipo.', 52);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-16', 'Llegar tarde de manera reiterada, lo cual puede generar problemas en la coordinación y en el flujo de trabajo.', 60);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-14', 'Incumplir con los plazos establecidos para la entrega de proyectos o tareas', 45);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-30', 'Llegar tarde de manera reiterada, lo cual puede generar problemas en la coordinación y en el flujo de trabajo.', 5);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-16', 'El empleado no se presenta al trabajo sin avisar o sin una razón válida, afectando la continuidad de las labores del equipo.', 61);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-12', 'Llegar tarde de manera reiterada, lo cual puede generar problemas en la coordinación y en el flujo de trabajo.', 48);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-12', 'No informar oportunamente sobre dificultades o retrasos que puedan afectar el cumplimiento de las metas', 41);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-14', 'No informar oportunamente sobre dificultades o retrasos que puedan afectar el cumplimiento de las metas', 70);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-30', 'El empleado no se presenta al trabajo sin avisar o sin una razón válida, afectando la continuidad de las labores del equipo.', 4);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-17', 'El empleado no se presenta al trabajo sin avisar o sin una razón válida, afectando la continuidad de las labores del equipo.', 57);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-14', 'No seguir las políticas o procedimientos establecidos por la empresa', 83);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-30', 'No informar oportunamente sobre dificultades o retrasos que puedan afectar el cumplimiento de las metas', 34);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-30', 'Incumplir con los plazos establecidos para la entrega de proyectos o tareas', 72);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-14', 'Cometer fallos en el trabajo de forma repetitiva, a pesar de haber sido señalados previamente', 35);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-30', 'No seguir las políticas o procedimientos establecidos por la empresa', 34);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-14', 'El empleado no se presenta al trabajo sin avisar o sin una razón válida, afectando la continuidad de las labores del equipo.', 44);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-14', 'Cometer fallos en el trabajo de forma repetitiva, a pesar de haber sido señalados previamente', 18);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-16', 'Llegar tarde de manera reiterada, lo cual puede generar problemas en la coordinación y en el flujo de trabajo.', 49);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-03-17', 'Llegar tarde de manera reiterada, lo cual puede generar problemas en la coordinación y en el flujo de trabajo.', 77);
INSERT INTO fault(doneDate, summary, faultUserIDFK) VALUES('2025-05-14', 'Incumplir con los plazos establecidos para la entrega de proyectos o tareas', 3);

-- query para conocer los usuarios que les toco responder una pregunta en especifico.
SELECT u.birthName, u.surname 
FROM user AS u, oneOnOne AS one, oneOnOneAnswer AS oneA, oneOnOneQuestion AS oneQ
WHERE oneQ.questionID = oneA.questionIDFK
AND oneA.answerOneOnOneIDFK = one.oneOnOneID
AND one.oneOnOneID = u.userID
AND oneQ.questionID = 6;

-- query para conocer los usuarios que les toco asistir en un día especifico a un one on one
SELECT u.birthName, u.surname, one.meetingDate
FROM user AS u, oneOnOne AS one
WHERE one.oneOnOneUserIDFK = u.userID
AND one.meetingDate BETWEEN '2025-03-20 00:00:00' AND '2025-03-20 23:59:59';