INSERT INTO privilege(title, summary) values('Colaborador consulta ausencias', 'Colaborador consulta ausencias.'); 
INSERT INTO privilege(title, summary) values('Colaborador consulta calendario', 'Colaborador consulta calendario.'); 
INSERT INTO privilege(title, summary) values('Colaborador consulta días feriados', 'Colaborador consulta días feriados.'); 
INSERT INTO privilege(title, summary) values('Colaborador consulta falta administrativa', 'Colaborador consulta falta administrativa'); 
INSERT INTO privilege(title, summary) values('Colaborador consulta KPIs', 'Colaborador consulta KPIs.'); 
INSERT INTO privilege(title, summary) values('Colaborador consulta perfil', 'Colaborador consulta perfil.'); 
INSERT INTO privilege(title, summary) values('Colaborador consulta sesión del One-On-One', 'Colaborador consulta sesión del One-On-One.'); 
INSERT INTO privilege(title, summary) values('Colaborador consulta solicitudes de vacaciones', 'Colaborador consulta solicitudes de vacaciones.'); 
INSERT INTO privilege(title, summary) values('Colaborador elimina solicitud de vacaciones', 'Colaborador elimina solicitud de vacaciones.'); 
INSERT INTO privilege(title, summary) values('Colaborador modifica contraseña temporal', 'Colaborador modifica contraseña temporal.'); 
INSERT INTO privilege(title, summary) values('Colaborador modifica solicitud de vacaciones', 'Colaborador modifica solicitud de vacaciones.'); 
INSERT INTO privilege(title, summary) values('Colaborador registra ausencia', 'Colaborador registra ausencia.'); 
INSERT INTO privilege(title, summary) values('Colaborador registra evidencia de KPI', 'Colaborador registra evidencia de KPI.'); 
INSERT INTO privilege(title, summary) values('Colaborador registra inicio de sesión', 'Colaborador registra inicio de sesión.'); 
INSERT INTO privilege(title, summary) values('Colaborador registra solicitud de vacaciones', 'Colaborador registra solicitud de vacaciones.'); 
INSERT INTO privilege(title, summary) values('Líder consulta ausencias de colaborador', 'Líder consulta ausencias de colaborador.'); 
INSERT INTO privilege(title, summary) values('Líder consulta colaboradores en su departamento', 'Líder consulta colaboradores en su departamento.'); 
INSERT INTO privilege(title, summary) values('Líder consulta KPIs de colaborador', 'Líder consulta KPIs de colaborador.'); 
INSERT INTO privilege(title, summary) values('Líder consulta perfil de colaboradores', 'Líder consulta perfil de colaboradores.'); 
INSERT INTO privilege(title, summary) values('Líder consulta solicitudes de vacaciones de colaborador', 'Líder consulta solicitudes de vacaciones de colaborador.'); 
INSERT INTO privilege(title, summary) values('Líder elimina KPIs de colaborador', 'Líder elimina KPIs de colaborador.'); 
INSERT INTO privilege(title, summary) values('Líder modifica KPIs de colaborador', 'Líder modifica KPIs de colaborador.'); 
INSERT INTO privilege(title, summary) values('Líder registra KPIs de colaborador', 'Líder registra KPIs de colaborador.'); 
INSERT INTO privilege(title, summary) values('Líder registra respuesta hacia ausencia de colaborador', 'Líder registra respuesta hacia ausencia de colaborador.'); 
INSERT INTO privilege(title, summary) values('Líder registra respuesta hacia solicitud de vacaciones de colaborador', 'Líder registra respuesta hacia solicitud de vacaciones de colaborador.'); 
INSERT INTO privilege(title, summary) values('Superadmin consulta ausencias de empleado', 'Superadmin consulta ausencias de empleado.'); 
INSERT INTO privilege(title, summary) values('Superadmin consulta empleados activos', 'Superadmin consulta empleados activos.'); 
INSERT INTO privilege(title, summary) values('Superadmin consulta empleados inactivos', 'Superadmin consulta empleados inactivos.'); 
INSERT INTO privilege(title, summary) values('Superadmin consulta reporte de rotación de empleos mensual', 'Superadmin consulta reporte de rotación de empleos mensual.'); 
INSERT INTO privilege(title, summary) values('Superadmin consulta sesión del One-On-One', 'Superadmin consulta sesión del One-On-One'); 
INSERT INTO privilege(title, summary) values('Superadmin consulta solicitudes de vacaciones de empleado', 'Superadmin consulta solicitudes de vacaciones de empleado.'); 
INSERT INTO privilege(title, summary) values('Superadmin elimina departamento', 'Superadmin elimina departamento.'); 
INSERT INTO privilege(title, summary) values('Superadmin Elimina día feriado', 'Superadmin elimina día feriado.'); 
INSERT INTO privilege(title, summary) values('Superadmin elimina falta administrativa', 'Superadmin elimina falta administrativa.'); 
INSERT INTO privilege(title, summary) values('Superadmin Elimina Kpi de líder', 'Superadmin elimina Kpi de líder.'); 
INSERT INTO privilege(title, summary) values('Superadmin modifica datos de empleado', 'Superadmin modifica datos de empleado.'); 
INSERT INTO privilege(title, summary) values('Superadmin modifica departamento', 'Superadmin modifica departamento.'); 
INSERT INTO privilege(title, summary) values('Superadmin Modifica día feriado', 'Superadmin modifica día feriado.'); 
INSERT INTO privilege(title, summary) values('Superadmin modifica falta administrativa', 'Superadmin modifica falta administrativa.'); 
INSERT INTO privilege(title, summary) values('Superadmin Modifica Kpi de líder', 'Superadmin modifica Kpi de líder.'); 
INSERT INTO privilege(title, summary) values('Superadmin registra alta de empleado', 'Superadmin registra alta de empleado.'); 
INSERT INTO privilege(title, summary) values('Superadmin registra baja de empleado', 'Superadmin registra baja de empleado.'); 
INSERT INTO privilege(title, summary) values('Superadmin registra datos del One-On-One', 'Superadmin registra datos del One-On-One.'); 
INSERT INTO privilege(title, summary) values('Superadmin registra departamento', 'Superadmin registra departamento.'); 
INSERT INTO privilege(title, summary) values('Superadmin Registra día feriado', 'Superadmin registra día feriado'); 
INSERT INTO privilege(title, summary) values('Superadmin registra falta administrativa', 'Superadmin registra falta administrativa.'); 
INSERT INTO privilege(title, summary) values('Superadmin registra fecha prevista de One-On-One', 'Superadmin registra fecha prevista de One-On-One.'); 
INSERT INTO privilege(title, summary) values('Superadmin Registra Kpi de líder', 'Superadmin registra Kpi de líder.'); 
INSERT INTO privilege(title, summary) values('Superadmin registra respuesta hacia ausencia de empleado', 'Superadmin registra respuesta hacia ausencia de empleado.'); 
INSERT INTO privilege(title, summary) values('Superadmin registra respuesta hacia solicitud de vacaciones de empleado', 'Superadmin registra respuesta hacia solicitud de vacaciones de empleado.'); 

INSERT INTO role(title) values('Colaborator'); 
INSERT INTO role(title) values('Department Leader'); 
INSERT INTO role(title) values('Human Resources'); 

INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 1); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 2); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 3); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 4); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 5); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 6); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 7); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 8); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 9); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 10); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 11); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 12); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 13); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 14); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 15); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 1); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 2); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 3); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 4); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 5); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 6); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 7); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 8); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 9); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 10); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 11); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 12); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 13); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 14); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 15); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 16); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 17); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 18); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 19); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 20); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 21); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 22); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 23); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 24); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 25); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 1); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 2); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 3); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 4); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 5); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 6); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 7); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 8); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 9); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 10); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 11); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 12); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 13); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 14); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 15); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 16); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 17); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 18); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 19); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 20); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 21); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 22); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 23); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 24); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 25); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 26); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 27); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 28); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 29); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 30); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 31); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 32); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 33); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 34); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 35); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 36); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 37); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 38); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 39); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 40); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 41); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 42); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 43); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 44); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 45); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 46); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 47); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 48); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 49); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 50); 

INSERT INTO country(title) values('Mexico'); 
INSERT INTO country(title) values('United States'); 
INSERT INTO country(title) values('Colombia'); 
INSERT INTO country(title) values('Argentina'); 

INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'González', 'dasjhjq@yahoo.com', 'xnnmnyuv', TRUE, 55485, '432.C', 'Calle de la Paz', 'Colonia Los Ángeles', 1, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Juan', 'Moreno', 'xorsyycpv@nuclea.solutions', 'waakmnjh', TRUE, 29345, '521.C', 'Avenida Revolución', 'Colonia Las Águilas', 3, TRUE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Jiménez', 'avyvgeq@nuclea.solutions', 'crfqhoaqgxix', FALSE, 91327, '640.A', 'Calle de la Luna', 'Colonia Santa Fe', 2, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Hernández', 'hfhfnowtfp@nuclea.solutions', 'nvxqogowf', TRUE, 37272, '607.A', 'Calle Juárez', 'Colonia Emiliano Zapata', 3, TRUE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Moreno', 'fvtvupclvbehs@nuclea.solutions', 'xpcpojxx', TRUE, 11482, '568.A', 'Calle de la Reforma', 'Colonia Los Ángeles', 1, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'Gómez', 'meynigjde@nuclea.solutions', 'ejgwomukk', FALSE, 54170, '15.A', 'Calle de la Virgen', 'Colonia del Sol', 3, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Torres', 'ooswxybw@nuclea.solutions', 'mrcbnmlgp', FALSE, 64455, '576.A', 'Avenida de la Luz', 'Colonia Los Ángeles', 0, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Rodríguez', 'plymmaqj@yahoo.com', 'auhnittx', TRUE, 71657, '807.A', 'Avenida de la Solidaridad', 'Colonia La Pradera', 1, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'González', 'jgsxjjhpfli@gmail.com', 'pfhfpbbpx', TRUE, 94363, '39.A', 'Calle Juárez', 'Colonia Lomas de Querétaro', 3, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Díaz', 'jasrbocj@yahoo.com', 'untlnbqyhjxq', TRUE, 57105, '719.B', 'Calle de los Naranjos', 'Colonia Valle Verde', 0, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Lucía', 'Fernández', 'wwsgabpgqmqq@outlook.com', 'dkjetvcnqkwt', TRUE, 89790, '750.B', 'Calle 5 de Febrero', 'Colonia Jardines de Querétaro', 3, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'González', 'tlwkcykjmbu@gmail.com', 'rfgnlukkqsk', TRUE, 20075, '982.A', 'Calle 5 de Febrero', 'Colonia El Cerrito', 0, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Torres', 'prxcwmgftsfi@yahoo.com', 'akhuxdfroeerd', TRUE, 94288, '166.A', 'Calle Corregidora', 'Colonia San Francisco', 3, TRUE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Torres', 'enxsilai@outlook.com', 'ftbiieacecasl', TRUE, 77374, '506.A', 'Avenida de los Insurgentes', 'Colonia Jardines de Querétaro', 0, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Rodríguez', 'nmcnumhwus@gmail.com', 'cuegagclnqr', TRUE, 36071, '606.A', 'Avenida de los Arcos', 'Colonia Santa Fe', 1, FALSE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Vázquez', 'auoencpclvr@yahoo.com', 'evqrnltgyijod', TRUE, 14771, '400.A', 'Calle Corregidora', 'Colonia Santa Fe', 1, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Díaz', 'priepcdqrw@yahoo.com', 'ipvxsvvvqn', FALSE, 98059, '116.B', 'Calle de la Santa Cruz', 'Colonia del Sol', 3, TRUE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'López', 'cqdtkdtw@nuclea.solutions', 'sbnqtbsdtk', FALSE, 35898, '39.C', 'Calle de la Santa Cruz', 'Colonia Santa Fe', 0, TRUE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Gómez', 'lcavhtualt@yahoo.com', 'ysdbogwbu', FALSE, 33284, '533.A', 'Calle Juárez', 'Colonia El Cerrito', 1, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'González', 'rhuycpa@yahoo.com', 'qxnnbim', TRUE, 93863, '94.A', 'Calle de la Santa Cruz', 'Colonia Los Ángeles', 3, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Lucía', 'Díaz', 'exauxpj@gmail.com', 'fmcfcrglhoh', TRUE, 23494, '573.A', 'Calle de la Amistad', 'Colonia Nuevo Milenio', 2, TRUE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Torres', 'kgqldqdmk@nuclea.solutions', 'poejxrqm', FALSE, 79088, '664.C', 'Calle de los Cedros', 'Colonia Valle Verde', 3, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'López', 'pqpaphos@yahoo.com', 'ettcnnopfawv', FALSE, 74938, '178.B', 'Calle de la Amistad', 'Colonia La Pradera', 2, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Hernández', 'yrxtamrojkqan@nuclea.solutions', 'xmaoscnqppgh', FALSE, 64485, '706.B', 'Calle de los Naranjos', 'Colonia Lomas de Querétaro', 3, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Díaz', 'pfdnpswy@nuclea.solutions', 'fulnglfefhsaw', FALSE, 57788, '320.C', 'Avenida de los Insurgentes', 'Colonia El Mirador', 0, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Martínez', 'rcejuejpn@gmail.com', 'arohbhjxm', FALSE, 16512, '475.B', 'Calle de la Virgen', 'Colonia Centro', 2, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Díaz', 'sngcgtoofodp@gmail.com', 'sgcapdooti', FALSE, 88851, '507.B', 'Avenida Universidad', 'Colonia Lomas de Querétaro', 3, TRUE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Alberto', 'González', 'rhegnvlfjj@gmail.com', 'jeeswell', TRUE, 40643, '940.A', 'Calle Allende', 'Colonia Nuevo Milenio', 3, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'Moreno', 'qebxqltx@outlook.com', 'yywgmktced', TRUE, 61495, '34.C', 'Avenida Constituyentes', 'Colonia Reforma', 3, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Díaz', 'ssyemyb@yahoo.com', 'haouvsbybo', FALSE, 60733, '52.C', 'Calle Guerrero', 'Colonia Emiliano Zapata', 3, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Vázquez', 'rrrqskyupd@outlook.com', 'rnapgeokujs', FALSE, 21240, '814.B', 'Calle de los Cedros', 'Colonia La Pradera', 2, TRUE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Sánchez', 'ojvjbyyfa@nuclea.solutions', 'noqjbjygdt', TRUE, 73509, '733.A', 'Avenida de la Solidaridad', 'Colonia Los Ángeles', 3, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'Pérez', 'jnbtocuveed@outlook.com', 'budbbiu', FALSE, 23940, '247.A', 'Avenida Morelos', 'Colonia La Pradera', 2, TRUE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'Moreno', 'qtuwaatbvrvu@nuclea.solutions', 'utreqtldjo', FALSE, 40665, '962.B', 'Calle de la Luna', 'Colonia San José', 1, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'López', 'gneaoct@gmail.com', 'cuhqtgj', FALSE, 17639, '70.C', 'Calle de la Esperanza', 'Colonia Reforma', 2, TRUE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Jiménez', 'tttpjth@nuclea.solutions', 'iqfdxxygiojq', FALSE, 64441, '505.C', 'Calle de la Esperanza', 'Colonia Morelos', 2, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Hernández', 'cfqlbyc@gmail.com', 'cqoewysirxbl', FALSE, 32597, '300.B', 'Avenida Morelos', 'Colonia Valle Verde', 2, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Díaz', 'fefkxslwumtg@nuclea.solutions', 'rswlepl', FALSE, 66163, '435.B', 'Avenida de los Arcos', 'Colonia El Laurel', 2, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Sánchez', 'qekeeisx@outlook.com', 'lugycjg', TRUE, 30850, '409.A', 'Calle de la Merced', 'Colonia del Sol', 0, TRUE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'Díaz', 'lqrcfxnf@gmail.com', 'estmrxxxgpqnd', TRUE, 30713, '566.B', 'Avenida Morelos', 'Colonia Centro', 3, TRUE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Pérez', 'dqndfudetjlju@yahoo.com', 'xgwexqrbql', FALSE, 22550, '332.A', 'Avenida Madero', 'Colonia Santa Fe', 2, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Gómez', 'mvyaftrjuj@nuclea.solutions', 'sfchoibeli', FALSE, 37716, '359.B', 'Calle de la Amistad', 'Colonia Emiliano Zapata', 0, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Gómez', 'bexwptsqlm@outlook.com', 'ebnjmvkekgf', TRUE, 20365, '925.C', 'Calle de la Paz', 'Colonia Morelos', 3, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Rodríguez', 'decsawmljdhej@yahoo.com', 'xlvjrcx', TRUE, 15075, '427.C', 'Calle Corregidora', 'Colonia Los Ángeles', 1, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'González', 'djpptuyxfi@gmail.com', 'ocduhib', TRUE, 20244, '606.B', 'Calle de la Luna', 'Colonia del Sol', 3, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Rodríguez', 'ckgjuvaxtfvb@outlook.com', 'idmplpcosmh', TRUE, 56254, '516.C', 'Calle de la Reforma', 'Colonia El Mirador', 1, TRUE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'López', 'oafplvtd@outlook.com', 'wqhgcpiovsju', TRUE, 25380, '677.C', 'Calle Juárez', 'Colonia Centro', 0, TRUE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Alberto', 'González', 'kiopvevedtty@outlook.com', 'rpdinxtkvdav', FALSE, 45813, '592.B', 'Avenida de la Solidaridad', 'Colonia del Sol', 0, FALSE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Jiménez', 'huclxvhyipqws@nuclea.solutions', 'frfdcynl', FALSE, 50709, '574.A', 'Calle de la Corregidora', 'Colonia El Mirador', 3, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Rodríguez', 'ruvtfnkch@gmail.com', 'jmrysat', TRUE, 96432, '999.A', 'Calle Zaragoza', 'Colonia Las Águilas', 2, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Hernández', 'ertqtdcyolc@outlook.com', 'tarturprhi', TRUE, 33010, '111.A', 'Calle 5 de Febrero', 'Colonia Valle Verde', 0, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'Fernández', 'doxiqmvs@gmail.com', 'jxlrixym', TRUE, 51990, '403.C', 'Calle de los Cedros', 'Colonia del Sol', 2, TRUE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Ruiz', 'widubiyyrapyc@nuclea.solutions', 'blhutiujbpm', FALSE, 91965, '98.B', 'Calle Vicente Guerrero', 'Colonia Centro', 3, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Sánchez', 'yifacgpckkg@nuclea.solutions', 'tdjotiw', FALSE, 32318, '214.C', 'Avenida de la Libertad', 'Colonia Santa Fe', 3, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'González', 'wgnbqxhwprx@yahoo.com', 'bwhlthrur', FALSE, 69442, '204.C', 'Calle 5 de Febrero', 'Colonia El Laurel', 0, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Jiménez', 'dsxuqxfjtckhg@outlook.com', 'vbwsvuqsdft', FALSE, 95326, '743.A', 'Calle de la Santa Cruz', 'Colonia Nuevo Milenio', 2, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'Vázquez', 'ktxogivcggwl@nuclea.solutions', 'axgvfjqdf', TRUE, 34447, '391.C', 'Calle de los Cedros', 'Colonia San José', 1, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Jiménez', 'dtplcmx@gmail.com', 'obrtjthfu', FALSE, 91503, '540.B', 'Calle de la Esperanza', 'Colonia Morelos', 1, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'González', 'fqpkdnbl@outlook.com', 'jvhdhemoyl', FALSE, 83942, '53.A', 'Calle de los Abetos', 'Colonia Lomas de Querétaro', 0, TRUE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Hernández', 'ivjscwv@yahoo.com', 'hcnnodoa', TRUE, 96998, '164.B', 'Calle Hidalgo', 'Colonia Centro', 1, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Moreno', 'vfysqrwpqmpaf@nuclea.solutions', 'wgynwqq', FALSE, 27966, '916.A', 'Calle Hidalgo', 'Colonia Santa Fe', 2, TRUE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Pérez', 'bnpiegchv@nuclea.solutions', 'tkxidupfpgyo', FALSE, 59947, '925.B', 'Calle de los Cedros', 'Colonia Centro', 2, TRUE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Fernández', 'pdbslxrp@outlook.com', 'aekrmkgjch', FALSE, 95053, '169.C', 'Calle de la Estación', 'Colonia Morelos', 1, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Gómez', 'sfjjswvt@outlook.com', 'vooiualeaetf', TRUE, 79084, '456.C', 'Avenida Revolución', 'Colonia Santa Fe', 3, TRUE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Pérez', 'utcpuury@nuclea.solutions', 'stgyvmtbskua', TRUE, 29998, '425.C', 'Avenida de la Juventud', 'Colonia Centro', 3, TRUE, 2, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'Hernández', 'odgjviqnakigd@gmail.com', 'fugiptdqpj', FALSE, 50184, '614.C', 'Avenida de los Insurgentes', 'Colonia Las Águilas', 3, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Moreno', 'gebsmhvmpmvjs@yahoo.com', 'xvomidrqo', FALSE, 55682, '305.C', 'Calle de la Reforma', 'Colonia El Mirador', 2, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Torres', 'wlnjhac@yahoo.com', 'olwemfiox', TRUE, 37396, '30.C', 'Avenida de los Insurgentes', 'Colonia Lomas de Querétaro', 3, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'López', 'sgghsqhwk@yahoo.com', 'fqemglwu', TRUE, 97564, '897.B', 'Avenida Morelos', 'Colonia Morelos', 2, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Ruiz', 'dbsxraxek@outlook.com', 'mwxukupu', TRUE, 44146, '74.B', 'Calle de la Paz', 'Colonia El Laurel', 3, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Vázquez', 'xdgywiwb@yahoo.com', 'kikvfcs', FALSE, 12613, '151.B', 'Calle de la Luna', 'Colonia Santa Rosa', 3, FALSE, 3, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'López', 'utabuwkryex@yahoo.com', 'rcncaug', FALSE, 82650, '272.B', 'Avenida Madero', 'Colonia El Mirador', 3, FALSE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'López', 'qhioiphqpafl@gmail.com', 'noljvgiqcjrw', TRUE, 96498, '726.B', 'Avenida de los Arcos', 'Colonia Lomas de Querétaro', 3, FALSE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Rodríguez', 'iagblshiudn@gmail.com', 'qdcomeftnwcdg', FALSE, 76762, '675.C', 'Calle Benito Juárez', 'Colonia El Campanario', 2, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Torres', 'fgspbvehuik@gmail.com', 'cothwqdfr', TRUE, 14187, '997.A', 'Avenida de la Luz', 'Colonia Santa Fe', 0, TRUE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Vázquez', 'bvacdsj@yahoo.com', 'xpjfjxoqeihgg', TRUE, 50200, '521.B', 'Calle Allende', 'Colonia El Mirador', 0, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'González', 'xsiuyqakvg@outlook.com', 'kvbccljirwytu', FALSE, 39974, '251.A', 'Avenida de los Arcos', 'Colonia Valle Verde', 2, TRUE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Alberto', 'Moreno', 'kybtvmirwjben@gmail.com', 'shrtdotcnmmk', TRUE, 12985, '981.A', 'Calle 5 de Febrero', 'Colonia El Laurel', 1, TRUE, 3, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Torres', 'tervkigcn@nuclea.solutions', 'olqdoberwa', TRUE, 59400, '41.C', 'Calle de los Pinos', 'Colonia El Mirador', 3, FALSE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Gómez', 'wrdlihegiig@nuclea.solutions', 'ryfxtcxyksfdo', TRUE, 65239, '420.C', 'Avenida de la Libertad', 'Colonia Santa Rosa', 0, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'Pérez', 'kaeqvckxtdc@yahoo.com', 'tjsyximwdqlna', FALSE, 94559, '214.B', 'Calle del Sol', 'Colonia Nuevo Milenio', 2, FALSE, 3, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Moreno', 'ddmhmgvlne@outlook.com', 'ppqergccghuf', FALSE, 63485, '523.B', 'Calle de los Abetos', 'Colonia El Laurel', 3, TRUE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Gómez', 'oyeapkxfabknj@outlook.com', 'eanlxuwfxa', FALSE, 86951, '106.B', 'Calle Allende', 'Colonia Nuevo Milenio', 1, TRUE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Vázquez', 'ofoyuafmknd@yahoo.com', 'wdxpnnqrpg', FALSE, 12164, '402.C', 'Calle Benito Juárez', 'Colonia Reforma', 2, FALSE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Fernández', 'ohxdtnjyrinsv@nuclea.solutions', 'ltfbcmrqt', FALSE, 22773, '446.A', 'Calle Vicente Guerrero', 'Colonia San Francisco', 1, TRUE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Ruiz', 'vcusjrcpjlkpr@nuclea.solutions', 'bbihtyqucnin', TRUE, 87359, '354.C', 'Calle de la Paz', 'Colonia San Francisco', 3, TRUE, 2, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Ruiz', 'uwvmhiwycjaem@nuclea.solutions', 'qdbfgyj', FALSE, 12978, '82.A', 'Calle del Carmen', 'Colonia Jardines de Querétaro', 2, FALSE, 1, 4);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Alberto', 'González', 'gfikphab@gmail.com', 'sxcxswvokfwje', FALSE, 88385, '457.A', 'Calle del Sol', 'Colonia Morelos', 1, TRUE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Alberto', 'Jiménez', 'ehplkqb@nuclea.solutions', 'bdqniowops', TRUE, 55753, '106.B', 'Avenida Universidad', 'Colonia La Pradera', 3, FALSE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Torres', 'ojgxyrisu@yahoo.com', 'odhatgo', TRUE, 18784, '871.C', 'Calle de los Pinos', 'Colonia Lomas de Querétaro', 1, FALSE, 1, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'López', 'mdwwxtmqhrb@yahoo.com', 'impigwyryn', FALSE, 36468, '824.A', 'Calle de la Esperanza', 'Colonia Las Águilas', 0, FALSE, 1, 3);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'López', 'weorqykpfjst@nuclea.solutions', 'svmrmqwbvvxwp', FALSE, 92594, '557.A', 'Avenida de la Libertad', 'Colonia El Mirador', 2, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Fernández', 'fexbxvprqah@gmail.com', 'tdskqgjwwcp', TRUE, 80723, '644.C', 'Avenida de la Luz', 'Colonia Santa Fe', 2, FALSE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'Moreno', 'bpybyvf@outlook.com', 'qmsucqjiwjj', TRUE, 74031, '271.C', 'Calle de la Virgen', 'Colonia Morelos', 0, TRUE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'González', 'ytacswh@gmail.com', 'lvdfhlcqw', TRUE, 13918, '332.A', 'Avenida Revolución', 'Colonia Santa Rosa', 1, TRUE, 2, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Lucía', 'Moreno', 'obeutvf@nuclea.solutions', 'mafrjtwaqycrt', TRUE, 73699, '467.C', 'Calle de la Esperanza', 'Colonia del Sol', 3, TRUE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'Rodríguez', 'pnfxpvpxnj@outlook.com', 'hukjlknegqbu', TRUE, 54123, '628.A', 'Calle de la Luna', 'Colonia Valle Verde', 2, FALSE, 1, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'Ruiz', 'amvjujnxv@nuclea.solutions', 'sstltrgdhvjh', TRUE, 40130, '424.C', 'Calle Corregidora', 'Colonia Santa Fe', 2, TRUE, 3, 2);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Torres', 'vnkthbkytj@outlook.com', 'vnwgminbnppl', TRUE, 99104, '487.C', 'Calle Juárez', 'Colonia Los Ángeles', 2, FALSE, 2, 1);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Roberto', 'Sánchez', 'pfkpyvtfb@yahoo.com', 'dovtgisqgi', TRUE, 34138, '222.A', 'Avenida de los Arcos', 'Colonia San Francisco', 0, FALSE, 3, 2);

