INSERT INTO privilege(title, summary) values('User B does this other thing', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('While user D still does this', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('User A does this', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('While user D still does this', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('User A does this', 'Another privilege more??'); 
INSERT INTO privilege(title, summary) values('And user C does this', 'Another privilege more??'); 
INSERT INTO privilege(title, summary) values('And user C does this', 'This is a privilege'); 
INSERT INTO privilege(title, summary) values('And user C does this', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('While user D still does this', 'This is another privilege'); 
INSERT INTO privilege(title, summary) values('While user D still does this', 'This is another privilege'); 

INSERT INTO role(title) values('Colaborator'); 
INSERT INTO role(title) values('Department Leader'); 
INSERT INTO role(title) values('Human Resources'); 

INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 4); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 9); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 10); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 6); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 10); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(3, 10); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(1, 7); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 6); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 6); 
INSERT INTO rolePrivilege(roleIDFK, privilegeIDFK) values(2, 9); 

INSERT INTO country(title) values('Mexico'); 
INSERT INTO country(title) values('United States'); 
INSERT INTO country(title) values('Colombia'); 
INSERT INTO country(title) values('Argentina'); 

INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Hernández', 'cvvalqiv@outlook.com', 'wcdybbmbgf', FALSE, 13774, '375.A', 'Calle de la Paz', 'Colonia Los Ángeles', 1, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Torres', 'rigjxqm@outlook.com', 'gbwksiojrngd', FALSE, 39083, '120.C', 'Calle Hidalgo', 'Colonia El Cerrito', 1, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'López', 'dqysiorhotwd@nuclea.solutions', 'inrqrgbhfd', FALSE, 13774, '239.B', 'Calle de la Esperanza', 'Colonia Reforma', 3, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Juan', 'López', 'orqgxyyil@yahoo.com', 'egbwxuinffram', TRUE, 11583, '415.A', 'Avenida de la Independencia', 'Colonia El Cerrito', 2, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Martínez', 'rmlgajwgfeqpg@gmail.com', 'wiotycldggg', TRUE, 37676, '505.B', 'Avenida Revolución', 'Colonia Reforma', 2, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Roberto', 'Pérez', 'nnoahbikrvlhg@outlook.com', 'vajisrg', FALSE, 20764, '419.B', 'Calle del Sol', 'Colonia El Mirador', 3, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'López', 'tbpiaqnm@yahoo.com', 'cmhqkybvharaw', TRUE, 26348, '416.A', 'Calle de la Corregidora', 'Colonia Jardines de Querétaro', 1, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Juan', 'Fernández', 'coyunyjhdlgqp@outlook.com', 'niittoejs', TRUE, 36083, '561.C', 'Avenida Morelos', 'Colonia Jardines de Querétaro', 3, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Pérez', 'nknijlr@gmail.com', 'rilcjwyu', FALSE, 23529, '553.B', 'Avenida de la Libertad', 'Colonia El Cerrito', 3, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'Jiménez', 'hffbfgwinqx@gmail.com', 'dmqovat', FALSE, 23428, '850.C', 'Avenida de la Solidaridad', 'Colonia del Sol', 3, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Torres', 'rvnlvjhpihkn@outlook.com', 'xoifplkiur', TRUE, 17500, '899.C', 'Calle de la Santa Cruz', 'Colonia San José', 1, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Martínez', 'ywrxojoxmp@yahoo.com', 'knbtighdd', TRUE, 18188, '881.C', 'Avenida Madero', 'Colonia La Pradera', 1, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Patricia', 'Fernández', 'ugobhqa@gmail.com', 'glrbyinwlds', FALSE, 19495, '653.B', 'Calle de la Merced', 'Colonia El Campanario', 1, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'Pérez', 'jlvbkxymoutf@outlook.com', 'gwhfdyxa', TRUE, 26812, '25.B', 'Calle de la Merced', 'Colonia Reforma', 3, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Lucía', 'Martínez', 'qdedujcbhf@yahoo.com', 'xlrlqcudj', TRUE, 14535, '886.A', 'Avenida Revolución', 'Colonia Santa Fe', 1, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Moreno', 'hojfyoxffj@outlook.com', 'vvubyvfxcg', FALSE, 32380, '528.C', 'Calle Guerrero', 'Colonia Nuevo Milenio', 2, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Fernández', 'lbpyxnydrloo@nuclea.solutions', 'wfqvorkc', TRUE, 19074, '754.C', 'Avenida de la Constitución', 'Colonia El Cerrito', 1, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Hernández', 'udjhgiwtp@gmail.com', 'mqsalej', FALSE, 12519, '449.B', 'Avenida de la Juventud', 'Colonia San José', 2, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Pérez', 'jcftkfkmy@gmail.com', 'dhxbsxyadgki', FALSE, 30042, '844.A', 'Calle Zaragoza', 'Colonia Los Ángeles', 1, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Pérez', 'extbhrw@nuclea.solutions', 'jdgnjvdy', FALSE, 37589, '865.A', 'Avenida de la Independencia', 'Colonia Jardines de Querétaro', 1, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'Gómez', 'bkrgxhfnsh@gmail.com', 'pphspvd', TRUE, 15160, '492.C', 'Calle del Sol', 'Colonia Los Ángeles', 3, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Díaz', 'glagkxfranyc@gmail.com', 'nmvcdmbpywam', TRUE, 16583, '941.A', 'Calle Vicente Guerrero', 'Colonia San José', 3, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Gómez', 'vtwukwoc@gmail.com', 'govbodvhay', TRUE, 10965, '86.C', 'Calle de la Amistad', 'Colonia Santa Rosa', 0, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'Torres', 'ggbsebebjxcr@gmail.com', 'vumshccaenum', TRUE, 42484, '8.B', 'Calle Benito Juárez', 'Colonia Los Ángeles', 0, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Hernández', 'pbjkospmuqp@yahoo.com', 'oevffugqbcww', FALSE, 36933, '170.A', 'Calle 5 de Febrero', 'Colonia La Pradera', 2, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Gómez', 'ckvdtoxt@gmail.com', 'sjndhlwph', FALSE, 41122, '830.C', 'Avenida de la Libertad', 'Colonia del Sol', 2, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Fernández', 'ckrytjhh@nuclea.solutions', 'vxofnpnckgw', FALSE, 13198, '431.B', 'Calle Juárez', 'Colonia Santa Fe', 2, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Fernández', 'ifyuihln@nuclea.solutions', 'npyxcekrsa', TRUE, 16527, '694.B', 'Calle Hidalgo', 'Colonia San José', 0, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'González', 'pkyeptfgnfc@outlook.com', 'gleiihsft', TRUE, 25070, '923.C', 'Calle de los Abetos', 'Colonia El Mirador', 1, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Gómez', 'bybdlqbruulh@yahoo.com', 'jxihjsekpu', TRUE, 21443, '77.A', 'Calle de la Esperanza', 'Colonia Santa Rosa', 0, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Gómez', 'itygxktmthd@gmail.com', 'cilbgmn', TRUE, 25652, '721.A', 'Calle Zaragoza', 'Colonia El Cerrito', 3, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Jiménez', 'gcyhywjqbhxbc@yahoo.com', 'kqoawaeflg', TRUE, 19984, '778.C', 'Avenida de la Luz', 'Colonia Jardines de Querétaro', 0, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Gómez', 'ngvvgfl@outlook.com', 'qndqsugr', TRUE, 41788, '717.C', 'Avenida de la Solidaridad', 'Colonia Reforma', 2, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'López', 'rckvkvnsetj@nuclea.solutions', 'otooppjeul', TRUE, 38685, '545.C', 'Calle Corregidora', 'Colonia San José', 1, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Alberto', 'Sánchez', 'gtxlxwf@gmail.com', 'ewtoccogtxsas', TRUE, 24289, '980.A', 'Avenida Constituyentes', 'Colonia Santa Rosa', 3, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Torres', 'oftilfxvqjj@nuclea.solutions', 'rnkaviy', FALSE, 10400, '313.B', 'Calle de los Abetos', 'Colonia Lomas de Querétaro', 3, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'González', 'llwhisuh@nuclea.solutions', 'encngxlolkbov', TRUE, 33754, '881.C', 'Calle del Carmen', 'Colonia Las Águilas', 0, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Isabel', 'Díaz', 'edrqxaq@gmail.com', 'acokadntnnjol', TRUE, 26344, '364.A', 'Calle de la Luna', 'Colonia San José', 0, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Gómez', 'tkaexfxhvk@yahoo.com', 'dsyucygcwgd', TRUE, 10435, '317.C', 'Calle del Carmen', 'Colonia Reforma', 3, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Vázquez', 'rprcaqvx@outlook.com', 'jdaaxysy', FALSE, 14634, '539.C', 'Calle Vicente Guerrero', 'Colonia El Campanario', 3, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Ruiz', 'kkiafklgatic@nuclea.solutions', 'qgibucdkesdmb', FALSE, 30111, '440.A', 'Calle Guerrero', 'Colonia Las Águilas', 1, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'González', 'hiwsiakc@yahoo.com', 'geapwtgfb', FALSE, 10555, '777.B', 'Avenida de la Constitución', 'Colonia Los Ángeles', 3, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Martínez', 'xpcxbac@nuclea.solutions', 'kvmbmhtk', FALSE, 16511, '720.C', 'Calle de la Paz', 'Colonia Nuevo Milenio', 0, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('María', 'Gómez', 'dgebvovb@outlook.com', 'pbehafpg', FALSE, 11780, '80.A', 'Calle Juárez', 'Colonia Reforma', 2, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Jiménez', 'qijomdkyeq@gmail.com', 'fdoxrcb', FALSE, 40247, '167.C', 'Calle de la Amistad', 'Colonia San José', 2, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Torres', 'cjdtoofjjutp@gmail.com', 'vidmprjelgof', FALSE, 32961, '757.C', 'Avenida Revolución', 'Colonia Morelos', 1, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Fernández', 'krjgkue@yahoo.com', 'fuuybbfhhbu', TRUE, 36363, '349.B', 'Calle Vicente Guerrero', 'Colonia Lomas de Querétaro', 3, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Gómez', 'dpgflvo@yahoo.com', 'ghhakylla', FALSE, 16056, '44.A', 'Avenida de la Independencia', 'Colonia Las Águilas', 1, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'González', 'ihmctug@nuclea.solutions', 'lwjimvhkqivyk', TRUE, 26479, '7.A', 'Calle Vicente Guerrero', 'Colonia Jardines de Querétaro', 2, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Rodríguez', 'kstoceqsh@gmail.com', 'npivyxtcam', FALSE, 27925, '76.A', 'Calle de los Cedros', 'Colonia Lomas de Querétaro', 0, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Lucía', 'Sánchez', 'rposbvpj@outlook.com', 'mqfnmhsc', TRUE, 42553, '359.C', 'Calle de los Cedros', 'Colonia San Francisco', 3, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Rodríguez', 'fuywkupqyg@outlook.com', 'bxspijgwycn', FALSE, 27630, '423.A', 'Calle Allende', 'Colonia Morelos', 0, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Sánchez', 'mqdgitkquppv@gmail.com', 'mstdtxmyg', FALSE, 38637, '749.C', 'Avenida Universidad', 'Colonia El Laurel', 1, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Sánchez', 'efvgiegrkxb@gmail.com', 'oikxngvhhpg', FALSE, 29801, '599.B', 'Calle Vicente Guerrero', 'Colonia Centro', 0, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Enrique', 'Moreno', 'ksnkslrikh@outlook.com', 'yfurhry', FALSE, 20706, '787.C', 'Avenida de la Independencia', 'Colonia Centro', 1, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'Vázquez', 'hxkmhnbr@nuclea.solutions', 'wjyshgk', TRUE, 27411, '9.C', 'Calle de la Corregidora', 'Colonia Nuevo Milenio', 3, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Torres', 'koylvtydico@gmail.com', 'epsvsogjans', FALSE, 38246, '711.B', 'Avenida de la Independencia', 'Colonia Santa Fe', 3, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Gómez', 'aplsqhhtudoc@nuclea.solutions', 'vlobtkoyticsd', TRUE, 27338, '438.B', 'Avenida Revolución', 'Colonia El Cerrito', 3, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Gómez', 'fcxwmwxcijg@nuclea.solutions', 'srwhrfqfcnat', FALSE, 32355, '645.B', 'Calle de los Naranjos', 'Colonia La Pradera', 2, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Gómez', 'tenigoy@nuclea.solutions', 'phbwljwfwerac', FALSE, 32376, '78.B', 'Calle de la Reforma', 'Colonia del Sol', 2, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Roberto', 'Sánchez', 'tgptdst@yahoo.com', 'rolmltjkdr', FALSE, 32746, '62.C', 'Calle de los Abetos', 'Colonia San José', 2, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Díaz', 'qhwepmcjbwooa@gmail.com', 'biyekchvysxg', FALSE, 29546, '95.C', 'Calle de los Abetos', 'Colonia El Cerrito', 0, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'Hernández', 'dkfpmqk@outlook.com', 'qokdlwwigaru', TRUE, 14027, '447.B', 'Avenida Revolución', 'Colonia Valle Verde', 0, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Ruiz', 'cphyxja@outlook.com', 'mtryidpdmecn', FALSE, 25530, '295.A', 'Calle Benito Juárez', 'Colonia Morelos', 1, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Beatriz', 'Hernández', 'crwjvnlnw@nuclea.solutions', 'nwdnvtfv', FALSE, 42288, '899.A', 'Calle Vicente Guerrero', 'Colonia La Pradera', 2, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Fernández', 'snugemn@yahoo.com', 'aamuxxoxqrl', FALSE, 24269, '365.A', 'Avenida Revolución', 'Colonia Las Águilas', 3, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Fernando', 'Jiménez', 'nfmuayinbi@outlook.com', 'dynlryihguh', TRUE, 30992, '775.B', 'Calle de la Luna', 'Colonia El Cerrito', 3, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'Hernández', 'mifdkxiwsj@gmail.com', 'lbpoktb', TRUE, 24079, '771.B', 'Calle de los Abetos', 'Colonia Los Ángeles', 2, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Laura', 'Vázquez', 'irslxpn@yahoo.com', 'vknlhybipapd', TRUE, 37364, '572.C', 'Calle de la Santa Cruz', 'Colonia Los Ángeles', 1, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Martínez', 'gdxnbfoq@yahoo.com', 'cplghqitl', TRUE, 31673, '762.A', 'Avenida de la Libertad', 'Colonia San José', 1, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Fernández', 'xdttwiibxagp@yahoo.com', 'gorwblchpnp', FALSE, 12580, '223.B', 'Avenida de la Luz', 'Colonia San Francisco', 2, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'López', 'jmwdnobith@outlook.com', 'jbtkolmnvk', TRUE, 19959, '344.A', 'Avenida de la Independencia', 'Colonia Centro', 0, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'López', 'nldvtwlfxpk@gmail.com', 'vyklefl', FALSE, 27010, '504.B', 'Calle de la Luna', 'Colonia Los Ángeles', 3, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'López', 'mqrbknglge@gmail.com', 'vstyutr', FALSE, 38071, '168.B', 'Calle Corregidora', 'Colonia Las Águilas', 2, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Torres', 'ltegwunq@gmail.com', 'utqxoidkn', TRUE, 29654, '885.B', 'Calle Vicente Guerrero', 'Colonia Los Ángeles', 3, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('José', 'Hernández', 'hcwkugqipsgk@outlook.com', 'hmaalqyrf', FALSE, 17156, '486.C', 'Calle Juárez', 'Colonia Reforma', 1, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Lucía', 'Gómez', 'oowwqkiyaaiov@gmail.com', 'tjqfuknabx', TRUE, 20809, '104.B', 'Calle del Carmen', 'Colonia Las Águilas', 1, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Jiménez', 'rbhnwnskbg@gmail.com', 'gbtqlod', TRUE, 20238, '358.B', 'Avenida Morelos', 'Colonia Santa Fe', 1, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'Rodríguez', 'bauinovbfpwd@outlook.com', 'mbtggqcgymfa', TRUE, 15498, '92.A', 'Avenida Morelos', 'Colonia del Sol', 3, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Francisco', 'Martínez', 'ovxhosywqysf@yahoo.com', 'ljulrfyo', FALSE, 11167, '222.B', 'Calle de la Amistad', 'Colonia Morelos', 0, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Moreno', 'rnbeujbyi@outlook.com', 'kdidbwb', TRUE, 36637, '337.A', 'Calle de la Corregidora', 'Colonia Morelos', 1, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'Jiménez', 'dukgkdbt@gmail.com', 'fbjmjgpgwes', TRUE, 39969, '24.C', 'Calle de la Paz', 'Colonia El Laurel', 1, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Sánchez', 'qvkqejfk@gmail.com', 'relquqiph', FALSE, 27125, '826.B', 'Calle de la Reforma', 'Colonia Los Ángeles', 0, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Pérez', 'tfvcslnnv@gmail.com', 'mxreivokagcf', FALSE, 27192, '367.A', 'Calle Allende', 'Colonia Santa Rosa', 0, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Ana', 'Martínez', 'yjsgxsueqooqq@outlook.com', 'iicgxqqrfaq', FALSE, 18317, '184.A', 'Calle del Carmen', 'Colonia Las Águilas', 0, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Adrián', 'Moreno', 'djivpnqcfyyka@nuclea.solutions', 'guuqsmn', TRUE, 14955, '701.B', 'Avenida Constituyentes', 'Colonia Los Ángeles', 0, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Sánchez', 'yaiyelln@nuclea.solutions', 'fxkuxtpwaaefo', TRUE, 21983, '926.A', 'Calle Hidalgo', 'Colonia Centro', 2, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Torres', 'sreoivwqssy@gmail.com', 'qtwcpua', TRUE, 17225, '873.A', 'Calle Vicente Guerrero', 'Colonia Santa Rosa', 3, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Sánchez', 'ufxevbkd@gmail.com', 'ppflngvaweuta', TRUE, 33784, '854.A', 'Calle Juárez', 'Colonia Reforma', 0, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Susana', 'Martínez', 'bqwyjvi@outlook.com', 'prcctxpywjolr', FALSE, 40379, '926.B', 'Calle Allende', 'Colonia Centro', 1, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Mercedes', 'Martínez', 'xcavmgu@yahoo.com', 'gcrsedpqfdiq', FALSE, 15913, '490.A', 'Calle de la Corregidora', 'Colonia El Cerrito', 2, FALSE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('David', 'González', 'ndmwlpv@yahoo.com', 'jefcrksqppdkb', TRUE, 36198, '846.C', 'Calle de la Santa Cruz', 'Colonia Los Ángeles', 3, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Raquel', 'López', 'guktdmr@yahoo.com', 'pgcgbufklhvdj', TRUE, 40284, '250.C', 'Calle de la Reforma', 'Colonia San Francisco', 3, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Carlos', 'González', 'gyooxasxu@yahoo.com', 'hjhiwguhs', FALSE, 31408, '80.A', 'Calle de la Amistad', 'Colonia Jardines de Querétaro', 0, TRUE, 2, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Elena', 'Pérez', 'uwqxfvdhjkuy@outlook.com', 'tyegrice', FALSE, 33468, '675.B', 'Calle de la Merced', 'Colonia San José', 0, FALSE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Juan', 'López', 'yllygbjmi@yahoo.com', 'rpkypnlajle', FALSE, 35921, '685.C', 'Calle de la Paz', 'Colonia Santa Fe', 3, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Pedro', 'Vázquez', 'kijtyoaspgf@nuclea.solutions', 'licevnecd', TRUE, 22077, '547.A', 'Calle 5 de Febrero', 'Colonia Las Águilas', 0, FALSE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Javier', 'Díaz', 'phvwiipcrncd@nuclea.solutions', 'ubowfvbixjs', TRUE, 19650, '883.C', 'Avenida de la Constitución', 'Colonia Jardines de Querétaro', 1, TRUE, 3, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Antonio', 'González', 'hobjriecrxpy@gmail.com', 'ikmbgnriwhtp', TRUE, 29665, '986.B', 'Calle de la Esperanza', 'Colonia Los Ángeles', 0, TRUE, 1, 189);
INSERT INTO user(birthName, surname, mail, passwd, passwdFlag, zipCode, houseNumber, streetName, colony, workModality, workStatus, userRoleIDFK, countryUserIDFK) VALUES('Rafael', 'Pérez', 'olgtvakwr@outlook.com', 'nctulidctgjbi', FALSE, 29530, '144.A', 'Avenida de la Libertad', 'Colonia Emiliano Zapata', 3, FALSE, 2, 189);

INSERT INTO oneOnOneQuestion(question) VALUES('¿Cuál va a ser tu meta del mes?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿El trabajo y las entregas van en el tiempo planeado?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Cuentas con los recursos necesarios para completar tu trabajo?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Cuál va a ser tu meta del mes?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Cuentas con los recursos necesarios para completar tu trabajo?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Estás preocupado, decepcionado o estresado?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿El trabajo y las entregas van en el tiempo planeado?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Qué vamos hacer para cumplir las metas?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Tuviste alguna situación complicada en tu semana que afectara en tu trabajo?'); 
INSERT INTO oneOnOneQuestion(question) VALUES('¿Qué vamos hacer para cumplir las metas?'); 

INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente excelente emocionalmente y con emociones muy positivas'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Reconocimiento: El colaborador se siente poco valorado por sus compañeros'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Equilibrio: El colaborador siente que hay mucho equilibrio entre su vida personal y trabajo'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Equilibrio: El colaborador siente que hay mucho equilibrio entre su vida personal y trabajo'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente bien emocionalmente y con emociones positivas'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente muy bien emocionalmente y con emociones positivas'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Reconocimiento: El colaborador se siente altamente valorado por sus compañeros'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente excelente emocionalmente y con emociones muy positivas'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica: El colaborador menciona tener una salud fisica mala'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Reconocimiento: El colaborador se siente valorado por sus compañeros'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente excelente emocionalmente y con emociones muy positivas'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Equiilibrio: El colaborador siente que hay poco equilibrio entre su vida personal y trabajo'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Carga de trabajo: El colaborador siente que su carga es medianamente manejable'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica: El colaborador menciona tener una salud fisica excelente'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud fisica: El colaborador menciona tener una salud fisica excelente'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Carga de trabajo El colaborador siente que su carga de trabajo no es manejable'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Reconocimiento: El colaborador se siente altamente valorado por sus compañeros'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente muy bien emocionalmente y con emociones positivas'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Carga de trabajo El colaborador siente que su carga de trabajo no es manejable'); 
INSERT INTO oneOnOneMeasurable(summary) VALUES('Salud emocional: El colaborador se siente regular emocionalmente y con emociones poco positivas'); 

INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:30:00', 83);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:15:00', 98);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:30:00', 89);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:15:00', 55);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:30:00', 79);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:30:00', 62);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:00:00', 35);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:45:00', 88);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:45:00', 49);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 32);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:30:00', 31);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:15:00', 66);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:15:00', 27);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:30:00', 47);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:15:00', 33);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:30:00', 19);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:30:00', 47);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:45:00', 20);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:30:00', 64);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:45:00', 21);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:45:00', 1);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 73);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 99);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:15:00', 18);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:30:00', 15);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:15:00', 81);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:45:00', 36);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:15:00', 83);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:15:00', 3);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:30:00', 95);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:30:00', 93);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:15:00', 31);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:30:00', 19);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:00:00', 6);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:00:00', 57);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:00:00', 37);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 54);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:15:00', 13);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:00:00', 77);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:30:00', 66);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-20 13:45:00', 94);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:30:00', 83);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-21 16:15:00', 14);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:15:00', 40);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 07:00:00', 36);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-07 14:30:00', 85);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:15:00', 53);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-05-12 14:30:00', 88);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 16);
INSERT INTO oneOnOne(expectedTime, meetingDate, oneOnOneUserIDFK) VALUES(15, '2025-03-05 09:45:00', 54);

INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Quiero concentrarme en perfeccionar mis habilidades técnicas y cumplir con los plazos establecidos en mis tareas.', 23, 1);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 21, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me siento orgulloso de haber cumplido mis objetivos en el proyecto X, lo que me permitió crecer profesionalmente.', 22, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('La mayoría de las entregas están en línea con el cronograma, aunque se requieren pequeños ajustes en algunas tareas.', 39, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 9, 1);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 8, 1);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Vamos a fomentar la comunicación continua y a utilizar herramientas de gestión que nos ayuden a monitorear el progreso.', 1, 3);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 24, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 37, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 7, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 24, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 40, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Quiero concentrarme en perfeccionar mis habilidades técnicas y cumplir con los plazos establecidos en mis tareas.', 11, 1);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Vamos a fomentar la comunicación continua y a utilizar herramientas de gestión que nos ayuden a monitorear el progreso.', 50, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Actualmente estoy enfocado en el desarrollo del proyecto Y, colaborando estrechamente con mi equipo para alcanzar los objetivos.', 19, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Estoy satisfecho por haber superado varios desafíos y mejorar mi organización y gestión del tiempo.', 16, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Planeamos definir un plan de acción detallado, distribuir responsabilidades claramente y realizar seguimientos semanales para ajustar el rumbo si es necesario.', 11, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Planeamos definir un plan de acción detallado, distribuir responsabilidades claramente y realizar seguimientos semanales para ajustar el rumbo si es necesario.', 7, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Quiero destacar el esfuerzo y la colaboración de todo el equipo, que ha sido fundamental para alcanzar los objetivos planteados.', 10, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, cuento con las herramientas y el apoyo necesario, lo que me permite avanzar sin mayores inconvenientes.', 31, 3);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Por el momento, estamos cumpliendo los plazos establecidos y el progreso es consistente.', 43, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 11, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('La mayoría de las entregas están en línea con el cronograma, aunque se requieren pequeños ajustes en algunas tareas.', 9, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 28, 7);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Por el momento, estamos cumpliendo los plazos establecidos y el progreso es consistente.', 40, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me encuentro trabajando en la optimización de procesos internos y en la implementación de mejoras para el próximo trimestre.', 44, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Sí, cuento con las herramientas y el apoyo necesario, lo que me permite avanzar sin mayores inconvenientes.', 45, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me siento orgulloso de haber cumplido mis objetivos en el proyecto X, lo que me permitió crecer profesionalmente.', 34, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 30, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Estoy satisfecho por haber superado varios desafíos y mejorar mi organización y gestión del tiempo.', 32, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Planeamos definir un plan de acción detallado, distribuir responsabilidades claramente y realizar seguimientos semanales para ajustar el rumbo si es necesario.', 21, 6);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En general, me siento tranquilo, aunque reconozco que en algunas situaciones se presenta algo de estrés que manejo con calma.', 32, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('La mayoría de las entregas están en línea con el cronograma, aunque se requieren pequeños ajustes en algunas tareas.', 5, 8);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 43, 1);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 37, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me encuentro trabajando en la optimización de procesos internos y en la implementación de mejoras para el próximo trimestre.', 25, 3);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('La mayoría de las entregas están en línea con el cronograma, aunque se requieren pequeños ajustes en algunas tareas.', 34, 5);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me encuentro trabajando en la optimización de procesos internos y en la implementación de mejoras para el próximo trimestre.', 39, 2);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 8, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En general tengo lo necesario, aunque en algunas áreas podría beneficiarme de recursos adicionales para acelerar ciertos procesos.', 18, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Por el momento, estamos cumpliendo los plazos establecidos y el progreso es consistente.', 41, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Planeamos definir un plan de acción detallado, distribuir responsabilidades claramente y realizar seguimientos semanales para ajustar el rumbo si es necesario.', 29, 6);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 6, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En general, me siento tranquilo, aunque reconozco que en algunas situaciones se presenta algo de estrés que manejo con calma.', 4, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Mi meta es finalizar el proyecto pendiente y comenzar a implementar nuevas estrategias para mejorar la productividad.', 39, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('En su mayoría la semana fue fluida, aunque surgió una situación que requirió reordenar prioridades, lo cual se solucionó rápidamente.', 15, 6);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Me encuentro trabajando en la optimización de procesos internos y en la implementación de mejoras para el próximo trimestre.', 11, 10);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Quiero destacar el esfuerzo y la colaboración de todo el equipo, que ha sido fundamental para alcanzar los objetivos planteados.', 34, 4);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Si bien hubo momentos de presión, no me siento decepcionado y estoy enfocado en encontrar soluciones.', 9, 9);
INSERT INTO oneOnOneAnswer(answer, answerOneOnOneIDFK, questionIDFK) VALUES('Quiero destacar el esfuerzo y la colaboración de todo el equipo, que ha sido fundamental para alcanzar los objetivos planteados.', 17, 10);

INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 26, 15);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 49, 11);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 4, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 11, 3);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 17, 18);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 26, 2);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 1, 20);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 16, 9);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 1, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 2, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 29, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 28, 8);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 1, 17);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 1, 20);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 37, 19);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 25, 10);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 48, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 28, 10);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 10, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 30, 14);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 21, 5);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 45, 18);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 34, 18);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 20, 1);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 36, 14);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 39, 9);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 38, 2);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 50, 10);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 5, 18);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 13, 7);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 41, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 49, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 23, 17);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 21, 9);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 22, 17);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(3, 27, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 39, 20);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 49, 2);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 33, 19);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 12, 15);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 19, 20);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 6, 6);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 9, 9);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(2, 4, 3);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(4, 42, 16);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 14, 16);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(1, 7, 13);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 26, 19);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 38, 3);
INSERT INTO oneOnOneMeasure(evaluation, measureOneOnOneIDFK, measurableIDFK) VALUES(5, 46, 6);

