@startuml CU02 - Superadmin registra alta de empleado
|Super Admin|
start
:Seleccionar registrar colaborador;
:Ingresa RFC del colaborador;
|#AntiqueWhite|Sistema|
if(¿Existe coincidencia en base de datos?) then 
->SI;
|Super Admin|
repeat:Registra datos requeridos por el sistema;
:Registra:
    - Nombre    
    - Apellido Paterno
    - Apellido Materno
    - Correo electrónico
    - Contraseña
    - Bandera de contraseña
    - Ciudad de trabajo
    - Modalidad de trabajo
    - Estado de trabajo;
:El Super Admin guarda los datos registrados;
|Sistema|
repeat while (¿Los campos estan completos?) is (NO)
->SI;
:Registra en la tabla USER de la base de datos la información recibida;
stop
else(NO)
:Muestra la coincidencia al Super Admin;
|Super Admin|
:Modifica de inactivo a activo;
stop

@enduml

