@startuml

|Lider|
start
:Selecciona "Vacation request";

|Sistema|
: Obtiene las peticiones de vacaciones de la tabla
vacations de la base de datos;

if(hay peticiones) then (si)
:Muestra la interfaz con las peticiones;

else (no)
:Muestra la interfaz con un mensaje
diciendo que no hay peticiones;

endif

|Lider|
stop
@enduml
