@startuml CU01 - Super admin registra alta de empleado
actor navegador
boundary employee.routes
boundary employeeAdd.ejs
boundary employee.ejs
control employee.controller
entity employeeModel
database mysql

autonumber
navegador -> employee.routes : GET /employee/add
activate employee.routes

employee.routes -> employee.controller: getAdd(request, response)
deactivate employee.routes
activate employee.controller

employee.controller -> employeeAdd.ejs: render(employeeAdd)
deactivate employee.controller
activate employeeAdd.ejs

employeeAdd.ejs -> navegador : Mostrar formulario para agregar colaborador
deactivate employeeAdd.ejs
activate navegador

navegador -> employee.routes : POST /employee/add (datos del colaborador)
deactivate navegador
activate employee.routes

employee.routes -> employee.controller : postAdd(request, response)
deactivate employee.routes
activate employee.controller

create employeeModel
employee.controller -> employeeModel : new Employee()
activate employeeModel

employee.controller ->> employeeModel : save()

employeeModel ->> mysql : INSERT INTO user(userID, curp, rfc, birthName,\nsurname, mail, passwd, passwdFlag, zipCode,\nhouseNumber, streetName,colony, workModality,\nworkStatus, userRoleIDFK, countryUserIDFK)
activate mysql
mysql -->> employeeModel : Insert OK
deactivate mysql
employeeModel -->> employee.controller : Empleado registrado
deactivate employeeModel

employee.controller -> employee.routes : response.redirect("/employee")
deactivate employee.controller
activate employee.routes
employee.routes -> employee.controller : getAdd(request, response)
deactivate employee.routes
activate employee.controller

employee.controller -> employee.ejs : response.render(employee)
deactivate employee.controller
activate employee.ejs


employee.ejs -> navegador : Mostrar notificacion "Empleado registrado exitosamente"
deactivate employee.ejs
@enduml