@startuml CU01 - Super admin registra alta de empleado
actor navegador
boundary employee.routes
boundary employeeAdd.ejs
control employee.controller
entity employeeModelInstance
database mysql

autonumber
navegador -> employee.routes : GET /employee/add
activate employee.routes

employee.routes -> employee.controller: getAdd(request, response)
deactivate employee.routes
activate employee.controller

employee.controller -> employeeAdd.ejs: render(employeeAdd)
deactivate employee.controller
activate employeeAdd.ejs

employeeAdd.ejs -> navegador : Mostrar formulario para agregar colaborador
deactivate employeeAdd.ejs
activate navegador

navegador -> employee.routes : POST /employee/add (datos del colaborador)
deactivate navegador
activate employee.routes

employee.routes -> employee.controller : postAdd(request, response)
deactivate employee.routes
activate employee.controller

employee.controller -> employeeModelInstance : new EmployeeModel()

employee.controller ->> employeeModelInstance : addEmployee(employeeData)
activate employeeModelInstance

employeeModelInstance ->> mysql : INSERT INTO user(userID, curp, rfc, birthName,\nsurname, mail, passwd, passwdFlag, zipCode,\nhouseNumber, streetName,colony, workModality,\nworkStatus, userRoleIDFK, countryUserIDFK)
activate mysql
mysql -->> employeeModelInstance : Insert OK
deactivate mysql
employeeModelInstance -->> employee.controller : Empleado registrado
deactivate employeeModelInstance

employee.controller -> employeeAdd.ejs : Mostrar mensaje "Empleado registrado exitosamente"
deactivate employee.controller
activate employeeAdd.ejs
activate navegador
employeeAdd.ejs -> navegador : Mostrar notificación
deactivate navegador
deactivate employeeAdd.ejs
deactivate employee.routes
@enduml