@startuml CU07 - Superadmin Registra dia feriado
actor navegador
boundary holiday.routes
boundary holidayAdd.ejs
control holiday.controller
entity holidayModelInstance
database mysql

autonumber
navegador -> holiday.routes : GET /holiday/add
activate holiday.routes

holiday.routes -> holiday.controller: getHolidaysAdd(req, res)
activate holiday.controller
deactivate holiday.routes

holiday.controller -> holidayAdd.ejs: render(holidayAdd)
deactivate holiday.controller
activate holidayAdd.ejs

holidayAdd.ejs -> navegador : Mostrar formulario dia feriado
deactivate holidayAdd.ejs
activate navegador

navegador -> holiday.routes : POST /holiday/add (datos del dia feriado)
deactivate navegador
activate holiday.routes

holiday.routes -> holiday.controller : postHolidayAdd(req, res)
deactivate holiday.routes
activate holiday.controller

holiday.controller -> holidayModelInstance : new HolidayModel()

holiday.controller ->> holidayModelInstance : insertar_diaFeriado(holidayData)
activate holidayModelInstance

holidayModelInstance ->> mysql : INSERT INTO usedHoliday (...)
activate mysql
mysql -->> holidayModelInstance : Insert OK
deactivate mysql
holidayModelInstance -->> holiday.controller : Dia Feriado registrado
deactivate holidayModelInstance

holiday.controller -> holidayAdd.ejs : Mostrar mensaje "Dia Feriado creado exitosamente"
activate holidayAdd.ejs
activate navegador
holidayAdd.ejs -> navegador : Mostrar notificación
deactivate navegador
deactivate holidayAdd.ejs
deactivate holiday.controller
deactivate holiday.routes
@enduml