@startuml CU28 - Superadmin modifica datos de empleado.
actor navegador
boundary employee.routes
boundary employeeCheckModify.ejs
control employee.controller
entity updatedEmployee
database mysql

autonumber
navegador -> employee.routes : GET /employee/:id/modify
activate employee.routes

employee.routes -> employee.controller: getModify(request, response)
deactivate employee.routes
activate employee.controller

employee.controller ->> updatedEmployee: fetchUser(request.param.id)
activate updatedEmployee

updatedEmployee ->> mysql: db.execute("SELECT * FROM user \nWHERE userID = ?", [userID]);
activate mysql

mysql -->> updatedEmployee: rows
deactivate mysql

updatedEmployee -->> employee.controller: rows
deactivate updatedEmployee

employee.controller -> employeeCheckModify.ejs: response.render("employeeCheckModify", rows)
deactivate employee.controller
activate employeeCheckModify.ejs

employeeCheckModify.ejs -> navegador : Mostrar formulario para modificar colaborador
deactivate employeeCheckModify.ejs
activate navegador

navegador -> employee.routes : POST /employee/:id/modify
deactivate navegador
activate employee.routes

employee.routes -> employee.controller : postModify(request, response)
deactivate employee.routes
activate employee.controller

employee.controller ->> updatedEmployee : updatedEmployee(request.params.id, request.body.curp, request.body.rfc, \nrequest.body.birthName,request.body.surname, reuquest.body.mail, \nrequest.body.passwd, request.body.passwdFlag, request.body.zipCode,\nrequest.body.houseNumber, request.body.streetName,request.body.colony, \nrequest.body.workModality, request.body.workStatus, request.body.userRoleIDFK, \nrequest.body.countryUserIDFK, request.body.workStatus)
activate updatedEmployee

updatedEmployee ->> mysql : db.execute("UPDATE user SET , curp = ?, rfc = ?, birthName = ?, \nsurname = ?, mail = ?, passwd = ?, passwdFlag = ?, \nzipCode = ?, houseNumber = ?, streetName = ?, \ncolony = ?, workModality = ?, userRoleIDFK = ?, \ncountryUserIDFK = ?, prioritaryDepartmentIDFK = ?, \nworkStatus = ? WHERE userID = ?;"), \n[curp,rfc,birthName,surname,mail,zipCode, \nhouseNumber,streetName,colony,workModality,\nuserRoleIDFK,countryUserIDFK,\nprioritaryDepartmentIDFK,workStatus,userID,]
activate mysql
mysql -->> updatedEmployee : Insert OK
deactivate mysql
updatedEmployee -->> employee.controller : Promesa
deactivate updatedEmployee

employee.controller -> employee.routes : response.redirect("/employee")
deactivate employee.controller
activate employee.routes
deactivate employee.routes
