@startuml CU30 - Superadmin modifica dia feriado
actor navegador
boundary holiday.routes
boundary holidayModify.ejs
boundary holiday.ejs
control holiday.controller
entity holiday
database mysql

autonumber
navegador -> holiday.routes : GET /holiday/:id/modify
activate holiday.routes

holiday.routes -> holiday.controller: getHolidaysModify(request, response)
deactivate holiday.routes
activate holiday.controller

holiday.controller -> holidayModify.ejs: response.render(holidayModify)
deactivate holiday.controller
activate holidayModify.ejs

holidayModify.ejs -> navegador : Mostrar formulario para modificar dia feriado
deactivate holidayModify.ejs
activate navegador

navegador -> holiday.routes : POST /holiday/add
deactivate navegador
activate holiday.routes

holiday.routes -> holiday.controller : postHolidayModify(request, response)
deactivate holiday.routes
activate holiday.controller
create holiday
holiday.controller -> holiday : new Holiday(request.body.usedHolidayID, \nrequest.body.usedDate, request.body.usedTemplateHolidayIDFK)
activate holiday

holiday.controller ->> holiday : save()

holiday ->> mysql : UPDATE usedHoliday (this.usedHolidayID, \nthis.usedDate, this.usedTemplateHolidayIDFK) \nVALUES(?, ?, ?)
activate mysql
mysql -->> holiday : Insert OK
deactivate mysql
holiday -->> holiday.controller : Promesa
deactivate holiday

holiday.controller -> holiday.routes : response.redirect("/holiday")
deactivate holiday.controller

@enduml