@startuml CU36 - Superadmin Registra dia feriado
actor navegador
boundary holiday.routes
boundary holidayAdd.ejs
boundary holiday.ejs
control holiday.controller
entity holidayModel
database mysql

autonumber
navegador -> holiday.routes : GET /holiday/add
activate holiday.routes

holiday.routes -> holiday.controller: getHolidaysAdd(request, response)
deactivate holiday.routes
activate holiday.controller

holiday.controller -> holidayAdd.ejs: response.render(holidayAdd)
deactivate holiday.controller
activate holidayAdd.ejs

holidayAdd.ejs -> navegador : Mostrar formulario dia feriado
deactivate holidayAdd.ejs
activate navegador

navegador -> holiday.routes : POST /holiday/add
deactivate navegador
activate holiday.routes

holiday.routes -> holiday.controller : postHolidayAdd(request, response)
deactivate holiday.routes
activate holiday.controller
create holidayModel
holiday.controller -> holidayModel : new Holiday(request.body.usedHolidayID, \nrequest.body.usedDate, request.body.usedTemplateHolidayIDFK)
activate holidayModel

holiday.controller ->> holidayModel : save()

holidayModel ->> mysql : INSERT INTO usedHoliday (this.usedHolidayID, \nthis.usedDate, this.usedTemplateHolidayIDFK) \nVALUES(?, ?, ?)
activate mysql
mysql -->> holidayModel : Insert OK
deactivate mysql
holidayModel -->> holiday.controller : Promesa
deactivate holidayModel

holiday.controller -> holiday.routes : response.redirect("/holiday")
deactivate holiday.controller

@enduml