@startuml
actor Navegador
boundary calendar.routes
boundary calendar.ejs
control calendar.controller
entity holiday.model
entity absence.model
entity vacation.model
entity oneToOne.model
database mysql

autonumber

activate Navegador
Navegador -> calendar.routes : GET /calendar
deactivate Navegador

activate calendar.routes
calendar.routes -> calendar.controller : getCalendar(req, res)
deactivate calendar.routes

activate calendar.controller

calendar.controller ->> holiday.model : fetchByDateType(startDate, endDate)
    activate holiday.model
    holiday.model ->> mysql : execute(VER QUERY)
        activate mysql
        mysql -->> holiday.model : rows
        deactivate mysql
    holiday.model -->> calendar.controller : holidayRows
    deactivate holiday.model
    
calendar.controller ->> absence.model : fetchByDateType(req.session.userID , startDate, endDate)
    activate absence.model
    absence.model ->> mysql : execute(VER QUERY)
        activate mysql
        mysql -->> absence.model : rows
        deactivate mysql
    absence.model -->> calendar.controller : absenceRows
    deactivate absence.model
    
calendar.controller ->> vacation.model : fetchByDateType(req.session.userID , startDate, endDate)
    activate vacation.model
    vacation.model ->> mysql : execute(VER QUERY)
        activate mysql
        mysql -->> vacation.model : rows
        deactivate mysql
    vacation.model -->> calendar.controller : vacationRows
    deactivate vacation.model
    
calendar.controller ->> oneToOne.model : fetchByDateType(req.session.userID , startDate, endDate)
    activate oneToOne.model
    oneToOne.model ->> mysql : execute(VER QUERY)
        activate mysql
        mysql -->> oneToOne.model : rows
        deactivate mysql
    oneToOne.model -->> calendar.controller : oneToOneRows
    deactivate oneToOne.model
    
calendar.controller -> calendar.ejs : res.render('calendar.ejs', VARIABLES)
deactivate calendar.controller

activate calendar.ejs
calendar.ejs -> Navegador: HTML
deactivate calendar.ejs

activate Navegador
deactivate Navegador
