@startuml
actor Navegador
boundary "vacation.routes" as Routes
boundary "addVacation.ejs" as Ejs
control "vacation.controller" as Controller
entity "vacation" as Model1
entity "vacation.model" as Model
database "mysql" as MySQL

autonumber

activate Navegador
Navegador -> Routes : GET /vacation/add
deactivate Navegador

activate Routes
Routes -> Controller : getAdd(request, response)
deactivate Routes

activate Controller

Controller ->> Model : fetchAvailableDays(request.session.userID)
activate Model
    Model ->> MySQL : execute(...);
    activate MySQL
        MySQL -->> Model : rows
    deactivate MySQL
    Model -->> Controller : rows
deactivate Model

Controller -> Ejs : response.render("addVacation.ejs", {...})
deactivate Controller

activate Ejs
Ejs -> Navegador : HTML
deactivate Ejs

activate Navegador
Navegador -> Routes : POST /vacation/add
deactivate Navegador

activate Routes
Routes -> Controller : postAdd(request, response)
deactivate Routes

activate Controller
create Model1
Controller -> Model1 : new Vacation(...)

activate Model1
Controller ->> Model1 : save()
Model1 ->> MySQL : execute(...)

activate MySQL
MySQL -->> Model1 : query OK
deactivate MySQL

Model1 -->> Controller : promesa
deactivate Model1

Controller -> Routes : response.redirect("/vacation")
deactivate Controller

@enduml