@startuml
|Colaborador|
start
:Selecciona la opción de “Solicitar vacaciones”;

|Sistema|
:Colaborador selecciona el periodo
para el que desea tomar vacaciones;
:Calcula la cantidad de días de vacaciones
disponibles para el periodo seleccionado;
if (¿Días disponibles > 0?) then (Sí)
    :Colaborador ingresa la fecha de
    inicio y finalización de sus vacaciones;
    :Colaborador registra el
    motivo de sus vacaciones;
    :Colaborador selecciona la
    opción de guardar información;
    :Recopila la información ingresada
    (fechas, motivo, ID del colaborador);
    :Crea un registro en la tabla “Vacations”;
    :Muestra un pop-up diciendo
    que el registro fue exitoso;
    :Colaborador selecciona la opción de
    cerrar registro de solicitud de vacaciones;
    :Redirige al colaborador
    a la página de calendario;
else (No)
    :Muestra un mensaje de error diciendo que
    el colaborador tiene días insuficientes;
    :Redirige al colaborador a la página de calendario;
    stop
endif

|Colaborador|
stop
@enduml