@startuml
|Superadmin|
start
:Selecciona la opción de
eliminar falta administrativa;

|Sistema|
:Consulta el rol del usuario;
if (¿Es Superadmin?) then (Sí)
    :Consulta el ID de la falta en la URL;
    :Elimina la falta con ese ID de la tabla “Faults”;
    :Muestra un pop-up diciendo
    que la eliminación fue exitosa;
else (No)
    :Redirige al usuario a una página de error 403;
    stop
endif

|Superadmin|
stop
@enduml