@startuml
|Líder|
start
:Seleccionar la opción de consultar \n perfil  del colaborador que el líder\n quiera ver  su perfil;

|Sistema|
:Consultar el ID del usuario que \nel líder seleccionó y con la tabla\n de user recopila sus datos personales;
:Recopilar la fecha de inicio de trabajo\n del colaborador con ayuda de la tabla workstatus;
:Recopilar la información del departamento\n para el que trabaja el colaborador\n con ayuda de la tabla userDepartment y department;
:Recopilar la infomación de las faltas con el\n ID de usuario y ayuda de la tabla fault;
:Generar y mostrar la interfaz del\n perfil del colaborador al líder;
stop
@enduml