@startuml
|Superadmin|
start
:Seleccionar la opcion de registrar \nfecha prevista del One-On-One;

|Sistema|
:Mostrar al superadmin la interfaz con\n el formulario para el registro;

|Superadmin|
:Ingresar datos para la reunion como:\n- Fecha y hora\n- Duracion;
:Ingresar la información del colaborador, como:\n- Nombre y apellido\n- Correo Electronico;
:Seleccionar la opción de guardar \nla información de la reunión;

|Sistema|
:Recopilar los datos del usuario y fecha  \ningresados por el superadmin;
:Obtener el ID del usuario buscandolo \ncon el nombre, apellido y correo electronico;
:Crear un registro en la tabla de \nOneOnOne con la información obtenida;
:Mostrar un mensaje de retroalimentación \npositivo al usuario;
:Redirigir al usuario a la pestaña \nde consultar OneOnOne;
stop
@enduml