@startuml
actor Navegador
boundary holiday.ejs
boundary holiday.routes
control holiday.controller
entity HolidayModel
database mysql

autonumber
' Inicio del flujo
activate Navegador
Navegador -> holiday.routes : GET /holiday/used
activate holiday.routes

holiday.routes -> holiday.controller : getUsedHoliday(req, res)
deactivate holiday.routes
activate holiday.controller

' Se renderiza la vista de días feriados
holiday.controller -> holiday.ejs : render(usedHoliday)
deactivate holiday.controller
activate holiday.ejs
holiday.ejs -> Navegador : HTML
deactivate Navegador
deactivate holiday.ejs


' Cargar los días feriados con paginación

Navegador -> holiday.routes : GET /holiday/search?page=1
activate Navegador
activate holiday.routes

holiday.routes -> holiday.controller : listPaginated(req, res)
deactivate holiday.routes
activate holiday.controller

holiday.controller ->> HolidayModel : getFaltasPaginated(limit, offset)
activate HolidayModel

HolidayModel ->> mysql : consulta sql
activate mysql
mysql -->> HolidayModel : Datos obtenidos
deactivate mysql

HolidayModel -->> holiday.controller : Retorna días feriados
deactivate HolidayModel


holiday.controller -->> Navegador : json
deactivate holiday.controller
deactivate Navegador


@enduml
