@startuml
actor navegador
boundary vacation.routes
boundary vacation.ejs
control vacation.controller
entity vacation.model
database mysql

autonumber
activate navegador
' Inicio del flujo
navegador -> vacation.routes : GET /vacations request
deactivate navegador
activate vacation.routes

vacation.routes -> vacation.controller : get_vacations(req, res)
deactivate vacation.routes
activate vacation.controller

vacation.controller ->> vacation.model : fetch_vacations_by_team(navegador_id)
activate vacation.model

' Consulta mejorada considerando solo colaboradores del mismo departamento
vacation.model ->> mysql : (Consulta sql)

activate mysql
mysql -->> vacation.model : Resultados (solicitudes)
deactivate mysql

vacation.model -->> vacation.controller : Lista de solicitudes
deactivate vacation.model

vacation.controller -> vacation.routes : res.render(vacations request)
deactivate vacation.controller
activate vacation.routes
vacation.routes -> navegador : HTML
deactivate vacation.routes
activate navegador
deactivate navegador
@enduml