@startuml
actor navegador
boundary addfault.ejs
boundary fault.routes
control fault.controller
entity faultModelInstance
database mysql

autonumber
' Inicio del flujo
activate navegador
navegador -> fault.routes : GET /fault/add
deactivate navegador

activate fault.routes

fault.routes -> fault.controller : getAdd(req,res)
deactivate fault.routes
activate fault.controller
fault.controller -> addfault.ejs: render(faultAdd)
deactivate fault.controller
activate addfault.ejs
addfault.ejs -> navegador : Mostrar formulario de falta
deactivate addfault.ejs
activate navegador
deactivate fault.routes

' Envío de datos de la falta
navegador -> fault.routes : POST /fault/add (datos de la falta)
deactivate navegador
activate fault.routes

fault.routes -> fault.controller : postAdd(req, res)
deactivate fault.routes
activate fault.controller

' Validación de campos
fault.controller -> fault.controller : Validar campos

alt Campos incompletos
    fault.controller -> addfault.ejs : mensaje de error "Completa todos los campos"
    deactivate fault.controller    
    activate addfault.ejs
    addfault.ejs -> navegador : HTML
    deactivate addfault.ejs
    deactivate fault.routes

else Campos completos
    ' Crear instancia del modelo
    activate fault.controller
    fault.controller -> faultModelInstance : new FaultModel(param)

    ' Verificar si el colaborador existe
    activate faultModelInstance
    fault.controller ->> faultModelInstance : save()
    deactivate fault.controller
    
    

    faultModelInstance -->> mysql : SELECT userID FROM user WHERE email = ?
    activate mysql
    mysql -->> faultModelInstance : Resultado
    
    deactivate mysql

    alt Colaborador no existe
        
        faultModelInstance -->> fault.controller : Error
        activate fault.controller
        fault.controller -> addfault.ejs : Mostrar mensaje de error "Error en los datos"
        deactivate fault.controller
        activate addfault.ejs
        addfault.ejs -> navegador : HTML
        deactivate addfault.ejs
        deactivate fault.controller
        deactivate fault.routes

    else Colaborador existe

        faultModelInstance ->> mysql : INSERT INTO fault (...)
        activate mysql
        mysql -->> faultModelInstance : Insert OK
        deactivate mysql
        faultModelInstance -->> fault.controller : Falta registrada
        activate fault.controller
        deactivate faultModelInstance

        ' Notificación de éxito
        fault.controller -> addfault.ejs : Mostrar mensaje "Falta creada exitosamente"
        deactivate fault.controller
        activate addfault.ejs
        addfault.ejs -> navegador : Mostrar notificación
        deactivate addfault.ejs
        deactivate fault.controller
        deactivate fault.routes
    end
end
@enduml
