@startuml
actor navegador
boundary faultAdd.ejs
boundary fault.routes
control fault.controller
entity faultModelInstance
database mysql

autonumber
' Inicio del flujo
activate navegador
navegador -> fault.routes : GET /fault/add
deactivate navegador

activate fault.routes

fault.routes -> fault.controller : getAdd(req,res)
deactivate fault.routes
activate fault.controller
fault.controller -> faultAdd.ejs: render(faultAdd)
deactivate fault.controller
activate faultAdd.ejs
faultAdd.ejs -> navegador : Mostrar formulario de falta
deactivate faultAdd.ejs
activate navegador
deactivate fault.routes

' Envío de datos de la falta
navegador -> fault.routes : POST /fault/add (datos de la falta)
deactivate navegador
activate fault.routes

fault.routes -> fault.controller : postAdd(req, res)
deactivate fault.routes
activate fault.controller

' Validación de campos
fault.controller -> fault.controller : Validar campos

alt Campos incompletos
    fault.controller -> faultAdd.ejs : mensaje de error "Completa todos los campos"
    deactivate fault.controller    
    activate faultAdd.ejs
    faultAdd.ejs -> navegador : HTML
    deactivate faultAdd.ejs
    deactivate fault.routes

else Campos completos
    ' Crear instancia del modelo

    fault.controller -> faultModelInstance : new FaultModel(param)
    activate fault.controller
    ' Verificar si el colaborador existe
    activate faultModelInstance
    fault.controller ->> faultModelInstance : save()
    deactivate fault.controller
    
    

    faultModelInstance -->> mysql : SELECT userID FROM user WHERE email = ?
    activate mysql
    mysql -->> faultModelInstance : Resultado
    
    deactivate mysql

    alt Colaborador no existe
        
        faultModelInstance -->> fault.controller : Error
        activate fault.controller
        fault.controller -> faultAdd.ejs : Mostrar mensaje de error "Error en los datos"
        deactivate fault.controller
        activate faultAdd.ejs
        faultAdd.ejs -> navegador : HTML
        deactivate faultAdd.ejs
        deactivate fault.controller
        deactivate fault.routes

    else Colaborador existe

        faultModelInstance ->> mysql : INSERT INTO fault (...)
        activate mysql
        mysql -->> faultModelInstance : Insert OK
        deactivate mysql
        faultModelInstance -->> fault.controller : Falta registrada
         deactivate faultModelInstance
        activate fault.controller
      

        ' Notificación de éxito
        fault.controller -> faultAdd.ejs : Mostrar mensaje "Falta creada exitosamente"
        deactivate fault.controller
        activate faultAdd.ejs
        faultAdd.ejs -> navegador : HTML
        deactivate faultAdd.ejs
        deactivate fault.controller
        deactivate fault.routes
    end
end
@enduml
