@startuml CU03 - Superadmin consulta empleado
|Super Admin|
start
:Selecciona consultar colaborador;
|Sistema|
if(¿Deseas visualizar a un colaborador en especifico?) then (SI)
    |Super Admin|
    :Selecciona si desea ver a los colaboradores activos o inactivos;
    |Sistema|
    if(¿Selecciono activo o inactivo?) then (Activo)
        :Despliega la lista de todos los empleados activos;
    else(Inactivo)
        :Despliega la lista de todos los empleados inactivo;
    endif
    stop
else(NO)
    |Sistema|
    :Muestra barra de busqueda;
    |Super Admin|
    :Ingresa el correo electrónico del colaborador;
    |Sistema|
    if(¿El correo electrónico esta registrado en la base de datos?) then (SI)
        :Muestra coincidencia al Super Admin;
        |Super Admin|
        :Selecciona al colaborador para ver todos sus datos;
        stop
    else(NO)
        |Sistema|
        :Le notifica al Super Admin que el correo que ingreso no existe;
        stop
@enduml