@startuml CU08 - Superadmin Registra evidencia de falta administrativa
|Super Admin|
start
repeat:Seleccionar añadir evidencia;
repeat:Registra evidencia;
:Guarda la evidencia;
|Sistema|
repeat while (¿Se cargo un archivo?) is (NO)
->SI;
repeat while (¿El formato es correcto?) is (NO)
->SI;
:Guarda la ruta donde se ubica el archivo en la base de datos;
stop
@enduml